import { providerFetch } from "./http";
import { ProviderConnection, providerConfigurationStatus, SocialProvider, SocialProviderError, UploadInput, UploadResult } from "./provider";

const AUTH_URL = "https://www.tiktok.com/v2/auth/authorize/";
const TOKEN_URL = "https://open.tiktokapis.com/v2/oauth/token/";
const USER_URL = "https://open.tiktokapis.com/v2/user/info/?fields=open_id,union_id,display_name,avatar_url";
const INBOX_INIT_URL = "https://open.tiktokapis.com/v2/post/publish/inbox/video/init/";

export class TikTokProvider implements SocialProvider {
  readonly id = "TIKTOK" as const;
  configurationStatus() { return providerConfigurationStatus("TIKTOK"); }
  private assertConfigured() { if (this.configurationStatus() === "NOT_CONFIGURED") throw new SocialProviderError("NOT_CONFIGURED", "TikTok não configurado."); }
  authorizationUrl(state: string) { this.assertConfigured(); const url = new URL(AUTH_URL); url.search = new URLSearchParams({ client_key: process.env.TIKTOK_CLIENT_KEY!, response_type: "code", scope: "user.info.basic,video.upload", redirect_uri: process.env.TIKTOK_REDIRECT_URI!, state }).toString(); return url; }
  async exchangeCode(code: string) { this.assertConfigured(); const body = new URLSearchParams({ client_key: process.env.TIKTOK_CLIENT_KEY!, client_secret: process.env.TIKTOK_CLIENT_SECRET!, code, grant_type: "authorization_code", redirect_uri: process.env.TIKTOK_REDIRECT_URI! }); const response = await providerFetch(TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }, "TikTok"); const token = await response.json() as Record<string, unknown>; if (!token.access_token) throw new SocialProviderError("PROVIDER_REJECTED", "TikTok não retornou um token válido."); return { accessToken: String(token.access_token), refreshToken: token.refresh_token ? String(token.refresh_token) : undefined, expiresAt: new Date(Date.now() + Number(token.expires_in ?? 86400) * 1000).toISOString() }; }
  async getAccountIdentity(connection: ProviderConnection) { const response = await providerFetch(USER_URL, { headers: { Authorization: `Bearer ${connection.accessToken}` } }, "TikTok"); const payload = await response.json() as { data?: { user?: Record<string, unknown> } }; const user = payload.data?.user; if (!user?.open_id) throw new SocialProviderError("PROVIDER_REJECTED", "TikTok não retornou a identidade da conta."); return { externalAccountId: String(user.open_id), displayName: String(user.display_name ?? "Conta TikTok"), username: undefined }; }
  async refresh(connection: ProviderConnection) { if (!connection.refreshToken) throw new SocialProviderError("AUTH_REQUIRED", "Reconecte sua conta TikTok."); const body = new URLSearchParams({ client_key: process.env.TIKTOK_CLIENT_KEY!, client_secret: process.env.TIKTOK_CLIENT_SECRET!, grant_type: "refresh_token", refresh_token: connection.refreshToken }); const response = await providerFetch(TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }, "TikTok"); const token = await response.json() as Record<string, unknown>; return { accessToken: String(token.access_token), refreshToken: String(token.refresh_token ?? connection.refreshToken), expiresAt: new Date(Date.now() + Number(token.expires_in ?? 86400) * 1000).toISOString() }; }
  async revoke(connection: ProviderConnection) { const body = new URLSearchParams({ client_key: process.env.TIKTOK_CLIENT_KEY!, client_secret: process.env.TIKTOK_CLIENT_SECRET!, token: connection.accessToken }); await providerFetch("https://open.tiktokapis.com/v2/oauth/revoke/", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }, "TikTok"); }
  async upload(connection: ProviderConnection, input: UploadInput): Promise<UploadResult> { if (input.bytes.length > 64 * 1024 * 1024) throw new SocialProviderError("INVALID_VIDEO", "O upload local inicial do TikTok aceita MP4 de até 64 MB por envio único."); const initResponse = await providerFetch(INBOX_INIT_URL, { method: "POST", headers: { Authorization: `Bearer ${connection.accessToken}`, "Content-Type": "application/json; charset=UTF-8" }, body: JSON.stringify({ source_info: { source: "FILE_UPLOAD", video_size: input.bytes.length, chunk_size: input.bytes.length, total_chunk_count: 1 } }) }, "TikTok"); const initialized = await initResponse.json() as { data?: { publish_id?: string; upload_url?: string } }; if (!initialized.data?.publish_id || !initialized.data.upload_url) throw new SocialProviderError("PROVIDER_REJECTED", "TikTok não iniciou o upload para revisão."); await providerFetch(initialized.data.upload_url, { method: "PUT", headers: { "Content-Type": "video/mp4", "Content-Length": String(input.bytes.length), "Content-Range": `bytes 0-${input.bytes.length - 1}/${input.bytes.length}` }, body: new Uint8Array(input.bytes) }, "TikTok"); return { externalPostId: initialized.data.publish_id, status: "SENT_FOR_REVIEW", metadata: { flow: "INBOX_UPLOAD" } }; }
}
