import { providerFetch } from "./http";
import { ProviderConnection, providerConfigurationStatus, SocialProvider, SocialProviderError, UploadInput, UploadResult } from "./provider";

const AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
const TOKEN_URL = "https://oauth2.googleapis.com/token";
const CHANNELS_URL = "https://www.googleapis.com/youtube/v3/channels?part=id,snippet&mine=true";
const UPLOAD_URL = "https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status";

export class YouTubeProvider implements SocialProvider {
  readonly id = "YOUTUBE" as const;
  configurationStatus() { return providerConfigurationStatus("YOUTUBE"); }
  private assertConfigured() { if (this.configurationStatus() === "NOT_CONFIGURED") throw new SocialProviderError("NOT_CONFIGURED", "YouTube não configurado."); }
  authorizationUrl(state: string) { this.assertConfigured(); const url = new URL(AUTH_URL); url.search = new URLSearchParams({ client_id: process.env.GOOGLE_CLIENT_ID!, redirect_uri: process.env.GOOGLE_REDIRECT_URI!, response_type: "code", scope: "https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube.readonly", access_type: "offline", include_granted_scopes: "true", prompt: "consent", state }).toString(); return url; }
  async exchangeCode(code: string) { this.assertConfigured(); const body = new URLSearchParams({ client_id: process.env.GOOGLE_CLIENT_ID!, client_secret: process.env.GOOGLE_CLIENT_SECRET!, code, grant_type: "authorization_code", redirect_uri: process.env.GOOGLE_REDIRECT_URI! }); const response = await providerFetch(TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }, "YouTube"); const token = await response.json() as Record<string, unknown>; if (!token.access_token) throw new SocialProviderError("PROVIDER_REJECTED", "Google não retornou um token válido."); return { accessToken: String(token.access_token), refreshToken: token.refresh_token ? String(token.refresh_token) : undefined, expiresAt: new Date(Date.now() + Number(token.expires_in ?? 3600) * 1000).toISOString() }; }
  async getAccountIdentity(connection: ProviderConnection) { const response = await providerFetch(CHANNELS_URL, { headers: { Authorization: `Bearer ${connection.accessToken}` } }, "YouTube"); const payload = await response.json() as { items?: Array<{ id: string; snippet?: { title?: string } }> }; const channel = payload.items?.[0]; if (!channel) throw new SocialProviderError("PROVIDER_REJECTED", "Nenhum canal YouTube foi encontrado para esta conta."); return { externalAccountId: channel.id, displayName: channel.snippet?.title ?? "Canal YouTube" }; }
  async refresh(connection: ProviderConnection) { if (!connection.refreshToken) throw new SocialProviderError("AUTH_REQUIRED", "Reconecte sua conta Google para conceder acesso offline."); const body = new URLSearchParams({ client_id: process.env.GOOGLE_CLIENT_ID!, client_secret: process.env.GOOGLE_CLIENT_SECRET!, refresh_token: connection.refreshToken, grant_type: "refresh_token" }); const response = await providerFetch(TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }, "YouTube"); const token = await response.json() as Record<string, unknown>; return { accessToken: String(token.access_token), refreshToken: connection.refreshToken, expiresAt: new Date(Date.now() + Number(token.expires_in ?? 3600) * 1000).toISOString() }; }
  async revoke(connection: ProviderConnection) { await providerFetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(connection.accessToken)}`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" } }, "Google"); }
  async upload(connection: ProviderConnection, input: UploadInput): Promise<UploadResult> { const metadata = { snippet: { title: input.title.slice(0, 100), description: input.description, categoryId: "24" }, status: { privacyStatus: "private", selfDeclaredMadeForKids: false } }; const init = await providerFetch(UPLOAD_URL, { method: "POST", headers: { Authorization: `Bearer ${connection.accessToken}`, "Content-Type": "application/json; charset=UTF-8", "X-Upload-Content-Length": String(input.bytes.length), "X-Upload-Content-Type": input.mimeType }, body: JSON.stringify(metadata) }, "YouTube"); const location = init.headers.get("location"); if (!location) throw new SocialProviderError("PROVIDER_REJECTED", "YouTube não retornou a sessão de upload."); const uploaded = await providerFetch(location, { method: "PUT", headers: { "Content-Type": input.mimeType, "Content-Length": String(input.bytes.length) }, body: new Uint8Array(input.bytes) }, "YouTube"); const video = await uploaded.json() as { id?: string; status?: { uploadStatus?: string } }; if (!video.id) throw new SocialProviderError("PROVIDER_REJECTED", "YouTube não retornou o videoId."); return { externalPostId: video.id, status: video.status?.uploadStatus === "uploaded" ? "PROCESSING" : "PROCESSING", metadata: { privacyStatus: "private" } }; }
}
