import { attachVideo, distributeContent, distributeVariant, feedback, generateMasterContent, generateVariants, saveContent, saveVariant } from "@/app/actions";
import { PendingButton } from "@/app/components/PendingButton";
import { all, one, Row } from "@/src/db";
import { getAIProvider } from "@/src/ai/provider";
import { integrationState } from "@/src/social/connections";
export const dynamic = "force-dynamic";

export default async function Studio({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const query = await searchParams;
  let content = one<Row>(`SELECT c.*,t.title topic_title,t.summary topic_summary,t.confidence_score,i.title idea_title,i.suggested_hook FROM contents c JOIN topics t ON t.id=c.topic_id JOIN ideas i ON i.id=c.idea_id WHERE c.id=?`, query.content || "content-a");
  const idea = query.idea ? one<Row>(`SELECT i.*,t.brand_id,t.title topic_title,t.summary topic_summary,t.confidence_score FROM ideas i JOIN topics t ON t.id=i.topic_id WHERE i.id=?`, query.idea) : undefined;
  if (!content && !idea) content = one<Row>(`SELECT c.*,t.title topic_title,t.summary topic_summary,t.confidence_score,i.title idea_title,i.suggested_hook FROM contents c JOIN topics t ON t.id=c.topic_id JOIN ideas i ON i.id=c.idea_id LIMIT 1`);
  const variants = content ? all<Row>("SELECT * FROM content_variants WHERE content_id=? ORDER BY CASE platform WHEN 'TIKTOK' THEN 1 WHEN 'YOUTUBE_SHORTS' THEN 2 ELSE 3 END", String(content.id)) : [];
  const assets = content ? all<Row>(`SELECT a.* FROM assets a JOIN content_variants v ON v.id=a.content_variant_id WHERE v.content_id=? ORDER BY a.created_at DESC`, String(content.id)) : [];
  const claims = content ? all<Row>("SELECT * FROM factual_claims WHERE content_id=?", String(content.id)) : [];
  const provider = getAIProvider(), tiktok = integrationState("TIKTOK"), youtube = integrationState("YOUTUBE"), data = content ?? idea!;
  return <div className="page"><div className="titleRow"><div><div className="eyebrow">CONTENT STUDIO · AI-FIRST</div><h1>{content ? "Revisar, editar e aprovar" : "Ideia escolhida"}</h1></div>{content && <span className="tag">{content.status}</span>}</div>
    <div className="flow"><b>TOPIC</b> → <b>IDEA</b> → <b>ANGLE</b> → <b>HOOK</b> → <b>MASTER</b> → <b>VARIANTS</b> → <b>MEDIA</b> → <b>DISTRIBUTION</b></div>
    {query.ai === "not-configured" && <div className="notice"><b>IA NÃO CONFIGURADA.</b> O conteúdo existente permanece intacto e editável.</div>}{query.upload === "invalid" && <div className="notice">Vídeo recusado. Envie um MP4 válido de até 500 MB.</div>}{query.distribution && <div className={query.distribution === "FAILED" ? "notice" : "successNotice"}>Distribuição: <b>{query.distribution}</b>. Consulte Publicações para detalhes.</div>}
    <div className="grid"><section className="panel span4"><div className="eyebrow">BASE FACTUAL</div><h2>{data.topic_title}</h2><p>{data.topic_summary}</p><div className="notice">Confiança: <b>{data.confidence_score}/100</b>. Claims incertos permanecem qualificados.</div>{idea && <><div className="eyebrow">IDEIA SELECIONADA</div><h2>{idea.title}</h2><p>{idea.angle}</p><blockquote>{idea.suggested_hook}</blockquote><form action={generateMasterContent}><input type="hidden" name="ideaId" value={String(idea.id)}/><PendingButton idle="GERAR CONTEÚDO" pending="GERANDO MASTER CONTENT..."/></form></>}</section>
      <section className="panel span8">{content ? <><form action={saveContent} className="formGrid"><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="brandId" value={String(content.brand_id)}/><input type="hidden" name="topicId" value={String(content.topic_id)}/><input type="hidden" name="ideaId" value={String(content.idea_id)}/><input type="hidden" name="status" value={String(content.status)}/><label className="full">Título<input name="title" required defaultValue={String(content.title)}/></label><label>Tese<textarea name="thesis" required defaultValue={String(content.thesis)}/></label><label>Ângulo<textarea name="angle" required defaultValue={String(content.angle)}/></label><label className="full">Master hook<textarea name="hook" required defaultValue={String(content.master_hook)}/></label><label className="full">Master script<textarea name="script" required style={{minHeight:180}} defaultValue={String(content.master_script)}/></label><label className="full">Caption base<textarea name="captionBase" defaultValue={String(content.caption_base ?? "")}/></label><button className="full secondary">SALVAR ALTERAÇÕES</button></form><div className="claims"><div className="eyebrow">FACTUAL CLAIMS</div>{claims.length ? claims.map(claim=><p key={String(claim.id)}><span className="badge">{claim.confidence}</span> {claim.claim_text}</p>) : <p className="muted">Claims serão persistidos na geração do conteúdo.</p>}</div><div className="actions"><form action={generateVariants}><input type="hidden" name="contentId" value={String(content.id)}/><PendingButton idle="GERAR VARIANTES" pending="ADAPTANDO PARA TIKTOK E SHORTS..."/></form><form action={feedback}><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="action" value="approved"/><button>APROVAR</button></form><form action={feedback}><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="action" value="rejected"/><select name="reason"><option>weak_hook</option><option>inaccurate</option><option>wrong_angle</option><option>not_hot_enough</option></select><button className="danger">REJEITAR</button></form></div></> : <p>Use “Gerar conteúdo” para a máquina preparar headline, hook, script, caption, claims e referências. Você poderá editar tudo.</p>}</section>
      {variants.map(variant => { const variantAssets = assets.filter(asset => asset.content_variant_id === variant.id), latestAsset = variantAssets[0]; return <section className={`panel span6 variantCard ${["TIKTOK","YOUTUBE_SHORTS"].includes(String(variant.platform))?"priorityVariant":""}`} key={String(variant.id)}><div className="eyebrow">{variant.platform} {["TIKTOK","YOUTUBE_SHORTS"].includes(String(variant.platform))&&"· PRIORITÁRIO"}</div><form action={saveVariant} className="formGrid"><input type="hidden" name="id" value={String(variant.id)}/><label className="full">Título<input name="title" defaultValue={String(variant.title)}/></label><label className="full">Hook<textarea name="hook" defaultValue={String(variant.hook)}/></label><label className="full">Script<textarea name="script" defaultValue={String(variant.script)}/></label><label className="full">Caption<textarea name="caption" defaultValue={String(variant.caption)}/></label><label>Hashtags<input name="hashtags" defaultValue={String(variant.hashtags)}/></label><label>CTA<input name="cta" defaultValue={String(variant.cta)}/></label><label>Duração<input name="duration" type="number" defaultValue={String(variant.target_duration ?? "")}/></label><label>Direção visual<input name="visual" defaultValue={String(variant.visual_direction)}/></label><button className="full secondary">SALVAR VARIANTE</button></form>{latestAsset ? <div className="videoAsset"><video controls preload="metadata" src={`/api/assets/${latestAsset.id}`}/><p><b>{latestAsset.original_filename}</b><small className="muted"> · {Math.round(Number(latestAsset.byte_size)/1024)} KB · {latestAsset.status}</small></p></div> : <form action={attachVideo} className="uploadBox"><input type="hidden" name="variantId" value={String(variant.id)}/><input type="hidden" name="contentId" value={String(content?.id)}/><label>ANEXAR VÍDEO MP4<input type="file" name="video" accept="video/mp4,.mp4" required/></label><PendingButton idle="ANEXAR VÍDEO" pending="VALIDANDO E ARMAZENANDO..."/></form>}</section>; })}
      {content && <section className="panel full distribution"><div className="eyebrow">DISTRIBUIÇÃO</div><h2>Escolha os destinos conectados</h2><p>Cada canal cria sua própria Publication. Falha em um canal não bloqueia o outro; idempotência impede reenvio do mesmo Asset.</p><form action={distributeContent} className="bulkDistribution"><input type="hidden" name="contentId" value={String(content.id)}/><label><input type="checkbox" name="providers" value="TIKTOK" disabled={!channelReady("TIKTOK",tiktok,variants,assets)}/> TikTok</label><label><input type="checkbox" name="providers" value="YOUTUBE" disabled={!channelReady("YOUTUBE_SHORTS",youtube,variants,assets)}/> YouTube Shorts</label><label className="muted"><input type="checkbox" disabled/> Instagram</label><label className="muted"><input type="checkbox" disabled/> Facebook</label><label className="muted"><input type="checkbox" disabled/> Kwai</label><PendingButton idle="DISTRIBUIR SELECIONADOS" pending="CRIANDO ENVIOS INDEPENDENTES..."/></form><div className="distributionGrid"><DistributionChannel name="TikTok" provider="TIKTOK" platform="TIKTOK" state={tiktok} variants={variants} assets={assets} contentId={String(content.id)}/><DistributionChannel name="YouTube Shorts" provider="YOUTUBE" platform="YOUTUBE_SHORTS" state={youtube} variants={variants} assets={assets} contentId={String(content.id)}/>{["Instagram","Facebook","Kwai"].map(name=><div className="channelRow mutedCard" key={name}><b>{name}</b><span>EM BREVE</span><button disabled>NÃO DISPONÍVEL</button></div>)}</div></section>}
    </div><p className="muted">Provider ativo: {provider.name}. Conteúdo de desenvolvimento é sempre identificado; nenhuma geração local é apresentada como IA real.</p></div>;
}

function DistributionChannel({ name, provider, platform, state, variants, assets, contentId }: { name: string; provider: "TIKTOK"|"YOUTUBE"; platform: string; state: ReturnType<typeof integrationState>; variants: Row[]; assets: Row[]; contentId: string }) { const variant = variants.find(item => item.platform === platform), asset = variant ? assets.find(item => item.content_variant_id === variant.id && item.status === "READY") : undefined, ready = state.status === "CONNECTED" && variant && asset; return <div className="channelRow"><div><b>{name}</b><small className="muted" style={{display:"block"}}>{state.displayName ?? state.status}</small></div>{ready ? <form action={distributeVariant}><input type="hidden" name="contentId" value={contentId}/><input type="hidden" name="provider" value={provider}/><input type="hidden" name="variantId" value={String(variant.id)}/><input type="hidden" name="assetId" value={String(asset.id)}/><PendingButton idle={provider === "TIKTOK" ? "ENVIAR PARA REVISÃO" : "PUBLICAR SHORT PRIVADO"} pending="ENVIANDO..."/></form> : <span className="configMissing">{state.status !== "CONNECTED" ? state.status : !variant ? "GERE A VARIANTE" : "ANEXE UM MP4"}</span>}</div>; }

function channelReady(platform: string, state: ReturnType<typeof integrationState>, variants: Row[], assets: Row[]) { const variant = variants.find(item => item.platform === platform); return state.status === "CONNECTED" && Boolean(variant && assets.some(asset => asset.content_variant_id === variant.id && asset.status === "READY")); }
