/* eslint-disable @next/next/no-img-element */
import { attachVideo, feedback, generateMasterContent, generateVariants, saveContent, saveVariant, startRender, pollRender, resolveMedia } from "@/app/actions";
import { PendingButton } from "@/app/components/PendingButton";
import { all, one, Row } from "@/src/db";
import { getAIProvider } from "@/src/ai/provider";
import { getRenderProvider } from "@/src/render/provider";
import { getAssetProvider } from "@/src/assets/provider";
import { composerPreview } from "@/src/render/provider";
import { loadResolvedAssets } from "@/src/assets/resolution";
import { renderPlanSchema } from "@/src/ai/schemas";
export const dynamic = "force-dynamic";

export default async function Studio({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const query = await searchParams;
  let content = one<Row>(`SELECT c.*,t.title topic_title,t.summary topic_summary,t.confidence_score,i.title idea_title,i.suggested_hook FROM contents c JOIN topics t ON t.id=c.topic_id JOIN ideas i ON i.id=c.idea_id WHERE c.id=?`, query.content || "content-a");
  const idea = query.idea ? one<Row>(`SELECT i.*,t.brand_id,t.title topic_title,t.summary topic_summary,t.confidence_score FROM ideas i JOIN topics t ON t.id=i.topic_id WHERE i.id=?`, query.idea) : undefined;
  if (!content && !idea) content = one<Row>(`SELECT c.*,t.title topic_title,t.summary topic_summary,t.confidence_score,i.title idea_title,i.suggested_hook FROM contents c JOIN topics t ON t.id=c.topic_id JOIN ideas i ON i.id=c.idea_id LIMIT 1`);
  const variants = content ? all<Row>("SELECT * FROM content_variants WHERE content_id=? ORDER BY CASE platform WHEN 'TIKTOK' THEN 1 WHEN 'YOUTUBE_SHORTS' THEN 2 ELSE 3 END", String(content.id)) : [];
  const assets = content ? all<Row>(`SELECT a.* FROM assets a JOIN content_variants v ON v.id=a.content_variant_id WHERE v.content_id=? ORDER BY a.created_at DESC`, String(content.id)) : [];
  const claims = content ? all<Row>("SELECT * FROM factual_claims WHERE content_id=?", String(content.id)) : [];
  const renderPlan = content ? one<Row>("SELECT * FROM render_plans WHERE content_id=? ORDER BY version DESC LIMIT 1", String(content.id)) : undefined;
  const render = content ? one<Row>("SELECT * FROM renders WHERE content_id=? ORDER BY created_at DESC LIMIT 1", String(content.id)) : undefined;
  const parsedPlan = renderPlan ? renderPlanSchema.safeParse(JSON.parse(String(renderPlan.plan_json))) : null;
  const preview = renderPlan && parsedPlan?.success ? composerPreview(parsedPlan.data, loadResolvedAssets(String(renderPlan.id))) : null;
  const provider = getAIProvider(), renderProvider = getRenderProvider(), assetProvider = getAssetProvider(), data = content ?? idea!;
  return <div className="page"><div className="titleRow"><div><div className="eyebrow">CONTENT STUDIO · AI-FIRST</div><h1>{content ? "Revisar, editar e aprovar" : "Ideia escolhida"}</h1></div>{content && <span className="tag">{content.status}</span>}</div>
    <div className="flow"><b>TOPIC</b> → <b>IDEA</b> → <b>ANGLE</b> → <b>HOOK</b> → <b>MASTER</b> → <b>VARIANTS</b> → <b>MEDIA</b> → <b>DISTRIBUTION</b></div>
    {query.media === "NEEDS_MEDIA" && <div className="notice">Há cenas obrigatórias sem mídia válida. O render permanece bloqueado.</div>}{query.media === "READY_TO_RENDER" && <div className="successNotice">Todas as mídias obrigatórias foram resolvidas. Conteúdo pronto para render.</div>}{query.generated === "all" && <div className="successNotice">Master Content, variantes e RenderPlan gerados automaticamente.</div>}{query.review === "render-required" && <div className="notice">A aprovação exige confirmação real de vídeo RENDERED.</div>}{query.renderError && <div className="notice" role="alert"><b>RENDER BLOQUEADO.</b> {renderErrorMessage(query.renderError)}</div>}{query.ai === "not-configured" && <div className="notice"><b>IA NÃO CONFIGURADA.</b> O conteúdo existente permanece intacto e editável.</div>}{query.upload === "invalid" && <div className="notice">Vídeo recusado. Envie um MP4 válido de até 500 MB.</div>}{query.distribution && <div className={query.distribution === "FAILED" ? "notice" : "successNotice"}>Distribuição: <b>{query.distribution}</b>. Consulte Publicações para detalhes.</div>}
    <div className="grid"><section className="panel span4"><div className="eyebrow">BASE FACTUAL</div><h2>{data.topic_title}</h2><p>{data.topic_summary}</p><div className="notice">Confiança: <b>{data.confidence_score}/100</b>. Claims incertos permanecem qualificados.</div>{idea && <><div className="eyebrow">IDEIA SELECIONADA</div><h2>{idea.title}</h2><p>{idea.angle}</p><blockquote>{idea.suggested_hook}</blockquote><form action={generateMasterContent}><input type="hidden" name="ideaId" value={String(idea.id)}/><PendingButton idle="GERAR CONTEÚDO" pending="GERANDO MASTER CONTENT..."/></form></>}</section>
      <section className="panel span8">{content ? <><form action={saveContent} className="formGrid"><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="brandId" value={String(content.brand_id)}/><input type="hidden" name="topicId" value={String(content.topic_id)}/><input type="hidden" name="ideaId" value={String(content.idea_id)}/><input type="hidden" name="status" value={String(content.status)}/><label className="full">Título<input name="title" required defaultValue={String(content.title)}/></label><label>Tese<textarea name="thesis" required defaultValue={String(content.thesis)}/></label><label>Ângulo<textarea name="angle" required defaultValue={String(content.angle)}/></label><label className="full">Master hook<textarea name="hook" required defaultValue={String(content.master_hook)}/></label><label className="full">Master script<textarea name="script" required style={{minHeight:180}} defaultValue={String(content.master_script)}/></label><label className="full">Caption base<textarea name="captionBase" defaultValue={String(content.caption_base ?? "")}/></label><button className="full secondary">SALVAR ALTERAÇÕES</button></form><div className="claims"><div className="eyebrow">FACTUAL CLAIMS</div>{claims.length ? claims.map(claim=><p key={String(claim.id)}><span className="badge">{claim.confidence}</span> {claim.claim_text}</p>) : <p className="muted">Claims serão persistidos na geração do conteúdo.</p>}</div><div className="actions"><form action={generateVariants}><input type="hidden" name="contentId" value={String(content.id)}/><PendingButton idle="GERAR VARIANTES" pending="ADAPTANDO PARA TIKTOK E SHORTS..."/></form><form action={feedback}><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="action" value="approved"/><button>APROVAR</button></form><form action={feedback}><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="action" value="rejected"/><select name="reason"><option>weak_hook</option><option>inaccurate</option><option>wrong_angle</option><option>not_hot_enough</option></select><button className="danger">REJEITAR</button></form></div></> : <p>Use “Gerar conteúdo” para a máquina preparar headline, hook, script, caption, claims e referências. Você poderá editar tudo.</p>}</section>
      {variants.map(variant => { const variantAssets = assets.filter(asset => asset.content_variant_id === variant.id), latestAsset = variantAssets[0]; return <section className={`panel span6 variantCard ${["TIKTOK","YOUTUBE_SHORTS"].includes(String(variant.platform))?"priorityVariant":""}`} key={String(variant.id)}><div className="eyebrow">{variant.platform} {["TIKTOK","YOUTUBE_SHORTS"].includes(String(variant.platform))&&"· PRIORITÁRIO"}</div><form action={saveVariant} className="formGrid"><input type="hidden" name="id" value={String(variant.id)}/><label className="full">Título<input name="title" defaultValue={String(variant.title)}/></label><label className="full">Hook<textarea name="hook" defaultValue={String(variant.hook)}/></label><label className="full">Script<textarea name="script" defaultValue={String(variant.script)}/></label><label className="full">Caption<textarea name="caption" defaultValue={String(variant.caption)}/></label><label>Hashtags<input name="hashtags" defaultValue={String(variant.hashtags)}/></label><label>CTA<input name="cta" defaultValue={String(variant.cta)}/></label><label>Duração<input name="duration" type="number" defaultValue={String(variant.target_duration ?? "")}/></label><label>Direção visual<input name="visual" defaultValue={String(variant.visual_direction)}/></label><button className="full secondary">SALVAR VARIANTE</button></form>{latestAsset ? <div className="videoAsset"><video controls preload="metadata" src={`/api/assets/${latestAsset.id}`}/><p><b>{latestAsset.original_filename}</b><small className="muted"> · {Math.round(Number(latestAsset.byte_size)/1024)} KB · {latestAsset.status}</small></p></div> : <form action={attachVideo} className="uploadBox"><input type="hidden" name="variantId" value={String(variant.id)}/><input type="hidden" name="contentId" value={String(content?.id)}/><label>ANEXAR VÍDEO MP4<input type="file" name="video" accept="video/mp4,.mp4" required/></label><PendingButton idle="ANEXAR VÍDEO" pending="VALIDANDO E ARMAZENANDO..."/></form>}</section>; })}
      {content && <section className="panel full"><div className="eyebrow">VIDEO COMPOSER PREVIEW</div><h2>Decisões de edição antes do render</h2>{renderPlan && parsedPlan?.success && preview ? <><p><b>{parsedPlan.data.version}</b> · {renderPlan.aspect_ratio} · {renderPlan.target_duration}s · <b>{preview.status}</b></p><div className="composerPreview">{preview.scenes.map(scene=><article className="composerScene" key={scene.order}><div className="eyebrow">CENA {scene.order} · {formatTime(scene.startSeconds)} – {formatTime(scene.startSeconds+scene.durationSeconds)}</div><b>{scene.visualType}</b>{scene.asset?.assetUrl ? scene.asset.assetType === "VIDEO"?<video muted controls preload="metadata" src={scene.asset.assetUrl}/>:<img src={scene.asset.assetUrl} alt={scene.caption}/>:<div className="notice">{scene.status === "MISSING_MEDIA" ? "MISSING MEDIA" : "CENA GRÁFICA"}</div>}<p><b>Texto:</b> {scene.headline??scene.caption}</p><p><b>Narração:</b> {scene.narration}</p><p><b>Asset query:</b> {scene.assetQuery||"—"}</p><p><b>Transition:</b> {scene.transition} · <b>Motion:</b> {scene.mediaMotion}</p><span className={scene.status==="READY"?"badge good":"badge uncertain"}>{scene.status}</span></article>)}</div>{render?.video_url?<video controls style={{width:"100%",maxHeight:560}} src={String(render.video_url)}/>:null}<div className="actions">{preview.status!=="READY"?<form action={resolveMedia}><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="renderPlanId" value={String(renderPlan.id)}/><PendingButton idle={assetProvider.available?"RESOLVER MÍDIAS":"MÍDIA NÃO CONFIGURADA"}/></form>:null}<form action={startRender}><input type="hidden" name="contentId" value={String(content.id)}/><PendingButton idle={renderProvider.available?"ENVIAR PARA RENDER":"RENDERIZAÇÃO NÃO CONFIGURADA"} disabled={preview.status!=="READY" || !renderProvider.available} className={preview.status!=="READY"?"composerDisabled":undefined}/>{preview.status!=="READY"&&<p className="muted">Render desabilitado até todas as cenas ficarem READY.</p>}</form>{content.status==="RENDERING"&&render?<form action={pollRender}><input type="hidden" name="contentId" value={String(content.id)}/><input type="hidden" name="renderId" value={String(render.id)}/><PendingButton idle="ATUALIZAR STATUS DO RENDER"/></form>:null}</div></>:renderPlan?<div className="notice">RenderPlan legado/inválido. Gere um Composer v1 antes de renderizar.</div>:<div className="notice">RenderPlan ainda não gerado.</div>}</section>}
      {content && <section className="panel full distribution"><div className="eyebrow">PUBLICAÇÃO</div><h2>Pipeline encerrado em APPROVED</h2><p>Publicação automática em TikTok e YouTube não faz parte desta etapa. As integrações oficiais existentes permanecem isoladas para evolução futura.</p></section>}
    </div><p className="muted">Provider ativo: {provider.name}. Conteúdo de desenvolvimento é sempre identificado; nenhuma geração local é apresentada como IA real.</p></div>;
}

function formatTime(seconds:number){return `${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,"0")}`}
function renderErrorMessage(code:string){const messages:Record<string,string>={RENDER_BLOCKED_MISSING_ASSET:"Uma ou mais cenas obrigatórias não possuem mídia válida.",RENDER_BLOCKED_DUPLICATE_MEDIA:"O mesmo asset foi usado em múltiplas cenas.",RENDER_BLOCKED_GENERIC_TEMPLATE:"Foi detectada mídia genérica, demo ou placeholder.",RENDER_BLOCKED_TEMPLATE_CONTRACT:"O template configurado não usa o contrato dark-media-composer-v1.",RENDER_BLOCKED_TIMELINE:"A timeline das cenas está inconsistente.",RENDER_BLOCKED_VOICE_OVERFLOW:"A narração não cabe na duração planejada.",RENDER_BLOCKED_VOICE_CONFIGURATION:"A voz ElevenLabs do plano não corresponde à voz configurada no template.",RENDER_NOT_CONFIGURED:"O Creatomate não está configurado."};return messages[code]??"A validação de segurança impediu o consumo de créditos."}
