import test from "node:test";
import assert from "node:assert/strict";
import { DevelopmentAIProvider, DisabledAIProvider } from "../src/ai/provider.ts";

const topic = { id: "topic-test", title: "Anúncio de artista fictícia", summary: "Menções crescem, ainda sem confirmação oficial.", confidenceScore: 32, viralityScore: 98, momentumScore: 96, saturationRisk: 18, freshness: "BREAKING", signals: ["rumor", "momentum"], sourceItems: [{ id: "source-item", title: "Buscas crescem", summary: "Não há confirmação primária.", url: null }], brand: { id: "brand-radar", name: "Radar Pop", tone: "Direto", targetAudience: "Brasil", editorialAggressiveness: "HIGH" } };

test("development provider returns exactly three ranked candidates and one recommendation", async () => { const provider = new DevelopmentAIProvider(); const candidates = await provider.generateIdeaCandidates(topic, 0); const ranked = await provider.rankIdeaCandidates(candidates, topic); assert.equal(ranked.length, 3); assert.equal(ranked.filter(candidate => candidate.recommendedCandidate).length, 1); assert.equal(ranked[0].recommendedCandidate, true); });
test("low-confidence candidates preserve uncertainty", async () => { const candidates = await new DevelopmentAIProvider().generateIdeaCandidates(topic, 0); assert.ok(candidates.every(candidate => candidate.warnings.some(warning => warning.includes("CONFIRMAÇÃO BAIXA")))); assert.match(candidates[0].suggestedHook, /rumor/i); assert.doesNotMatch(candidates[0].title, /confirma/i); });
test("selected idea produces master content, claims, references and distinct priority variants", async () => { const provider = new DevelopmentAIProvider(), idea = (await provider.generateIdeaCandidates(topic, 0))[0], content = await provider.generateContentFromIdea(topic, idea), variants = await provider.generatePlatformVariants(content); assert.ok(content.masterScript); assert.equal(content.factualClaims.length, 1); assert.deepEqual(content.sourceReferences, ["source-item"]); assert.deepEqual(variants.map(variant => variant.platform), ["TIKTOK", "YOUTUBE_SHORTS"]); assert.notEqual(variants[0].hook, variants[1].hook); });
test("disabled provider reports missing configuration without fake output", async () => { const provider = new DisabledAIProvider(); assert.equal(provider.available, false); await assert.rejects(provider.generateIdeaCandidates(topic, 0), /IA NÃO CONFIGURADA/); });
