import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DisabledAssetProvider, PexelsAssetProvider } from "../src/assets/provider.ts";
import { resolutionState } from "../src/assets/resolution.ts";
import { CREATOMATE_TEMPLATE_CONTRACT, CreatomateProvider, renderModifications } from "../src/render/provider.ts";

const scene = (order, visualType = "BRAND") => ({ order, text:`Scene ${order}`, durationSeconds:5, visualType, assetQuery:visualType === "STOCK" ? "football stadium" : "", caption:`Scene ${order}`, captionPosition:"CENTER", transition:"cut", voiceOverText:`Voice ${order}` });
const plan = { aspectRatio:"9:16", targetDuration:10, backgroundAudio:{mood:"news",volume:.2}, branding:{brandName:"Radar",primaryColor:"#fff",fontFamily:"Inter",logoAssetUrl:null}, scenes:[scene(1,"STOCK"),scene(2)] };
const resolved = [{sceneOrder:1,query:"football stadium",provider:"PEXELS",assetUrl:"https://cdn.test/stadium.mp4",assetType:"VIDEO",attribution:"Creator",licenseMetadata:{license:"Pexels"},status:"RESOLVED"},{sceneOrder:2,query:"",provider:"NONE",assetUrl:null,assetType:null,attribution:null,licenseMetadata:{},status:"NOT_REQUIRED"}];

test("absence of asset provider is explicit and never returns media",async()=>{const provider=new DisabledAssetProvider();assert.equal(provider.available,false);await assert.rejects(provider.resolve({query:"x",preferredKind:"IMAGE"}),error=>error.code==="ASSET_PROVIDER_NOT_CONFIGURED")});
test("Pexels resolves a usable asset with attribution and license metadata",async()=>{const fetcher=async()=>new Response(JSON.stringify({photos:[{id:7,url:"https://pexels.test/photo",photographer:"Creator",photographer_url:"https://pexels.test/creator",src:{portrait:"https://images.pexels.test/photo.jpg"}}]}));const asset=await new PexelsAssetProvider("secret",fetcher).resolve({query:"stadium",preferredKind:"IMAGE"});assert.equal(asset.url,"https://images.pexels.test/photo.jpg");assert.equal(asset.attribution,"Creator");assert.equal(asset.licenseMetadata.license,"Pexels License")});
test("Pexels requests time out with a safe provider error",async()=>{const previous=process.env.ASSET_PROVIDER_TIMEOUT_MS;process.env.ASSET_PROVIDER_TIMEOUT_MS="5";try{const fetcher=(_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener("abort",()=>reject(new DOMException("aborted","AbortError")),{once:true}));await assert.rejects(new PexelsAssetProvider("secret",fetcher).resolve({query:"stadium",preferredKind:"IMAGE"}),error=>error.code==="ASSET_PROVIDER_TIMEOUT"&&!error.message.includes("secret"))}finally{if(previous===undefined)delete process.env.ASSET_PROVIDER_TIMEOUT_MS;else process.env.ASSET_PROVIDER_TIMEOUT_MS=previous}});
test("missing required asset produces NEEDS_MEDIA",()=>{assert.deepEqual(resolutionState(plan,[]),{status:"NEEDS_MEDIA",missingSceneOrders:[1]})});
test("complete required assets produce READY_TO_RENDER",()=>{assert.deepEqual(resolutionState(plan,resolved),{status:"READY_TO_RENDER",missingSceneOrders:[]})});
test("RenderScript modifications use real properties and never assetQuery",()=>{const modifications=renderModifications(plan,resolved);assert.equal(modifications["Brand.text"],"Radar");assert.equal(modifications["Scene-1.Media.source"],"https://cdn.test/stadium.mp4");assert.equal(modifications["Scene-1.Media.duration"],5);assert.equal(modifications["Scene-1.Text.text"],"Scene 1");assert.equal(modifications["Scene-1.Text.duration"],5);assert.equal(modifications["Scene-1.VoiceOver.source"],"Voice 1");assert.equal(Object.keys(modifications).some(key=>key.includes("AssetQuery")||key.endsWith(".Duration")||key==="Scene-1.Media"),false);assert.equal(JSON.stringify(modifications).includes("football stadium"),false)});
test("render is prevented when required media or v2 contract is missing",async()=>{const provider=new CreatomateProvider("secret","template",async()=>{throw new Error("fetch must not run")},CREATOMATE_TEMPLATE_CONTRACT);await assert.rejects(provider.submit(plan,[]),error=>error.code==="CREATOMATE_MEDIA_REQUIRED");const incompatible=new CreatomateProvider("secret","template",async()=>{throw new Error("fetch must not run")},"dark-media-v1");await assert.rejects(incompatible.submit(plan,resolved),error=>error.code==="CREATOMATE_TEMPLATE_CONTRACT_INVALID")});
test("more than six scenes fails before calling Creatomate",async()=>{const oversized={...plan,targetDuration:35,scenes:Array.from({length:7},(_,index)=>scene(index+1))};const provider=new CreatomateProvider("secret","template",async()=>{throw new Error("fetch must not run")},CREATOMATE_TEMPLATE_CONTRACT);await assert.rejects(provider.submit(oversized,[]),error=>error.code==="CREATOMATE_SCENE_LIMIT_EXCEEDED"&&/no máximo 6/.test(error.message))});
test("Creatomate submit and polling use v2 endpoints and only succeeded with URL renders",async()=>{const calls=[];let payload;const fetcher=async(url,init)=>{calls.push(String(url));if(init?.method==="POST"){payload=JSON.parse(init.body);return new Response(JSON.stringify([{id:"real-id"}]),{status:200})}return new Response(JSON.stringify({id:"real-id",status:"succeeded",url:"https://cdn.test/render.mp4"}),{status:200})};const provider=new CreatomateProvider("secret","template",fetcher,CREATOMATE_TEMPLATE_CONTRACT);const submitted=await provider.submit(plan,resolved);assert.equal(submitted.status,"RENDERING");const completed=await provider.status("real-id");assert.equal(completed.status,"RENDERED");assert.equal(completed.videoUrl,"https://cdn.test/render.mp4");assert.deepEqual(calls,["https://api.creatomate.com/v2/renders","https://api.creatomate.com/v2/renders/real-id"]);assert.equal(payload.modifications["Scene-1.Media.source"],resolved[0].assetUrl);assert.equal(JSON.stringify(payload).includes("football stadium"),false)});
test("provider source contains no legacy v1 renders endpoint",()=>{const source=readFileSync("src/render/provider.ts","utf8");assert.doesNotMatch(source,/api\.creatomate\.com\/v1\/renders/)});
