import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";

function database() { const db = new DatabaseSync(":memory:"); db.exec(readFileSync("migrations/001_initial.sql", "utf8")); db.exec(readFileSync("migrations/002_ai_first_distribution.sql", "utf8")); db.exec("INSERT INTO workspaces(id,name) VALUES('w','W'); INSERT INTO brands(id,workspace_id,name,niche,target_audience,persona,tone,editorial_aggressiveness,controversy_appetite,virality_priority,freshness_priority,target_platforms) VALUES('b','w','B','N','A','P','T','HIGH','HIGH','HIGH','VERY_HIGH','TIKTOK,YOUTUBE_SHORTS'); INSERT INTO topics(id,brand_id,title,summary,category,first_detected_at,last_information_at,collected_at,freshness,virality_score,confidence_score,momentum_score,saturation_risk,editorial_priority_score) VALUES('t','b','T','S','C',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'BREAKING',98,32,96,18,94); INSERT INTO sources(id,brand_id,name,type,priority,reliability,category) VALUES('s','b','S','MANUAL',50,50,'C'); INSERT INTO source_items(id,source_id,title,summary) VALUES('si','s','SI','Fact'); INSERT INTO topic_source_items(topic_id,source_item_id) VALUES('t','si');"); return db; }

test("candidate selection, content, variants and asset persist relationally", () => { const db = database(); db.exec("INSERT INTO ideas(id,topic_id,title,angle,status,suggested_hook,supporting_facts,warnings,recommended,generation_batch_id,generated_by) VALUES('i','t','I','A','SELECTED','H','[]','[]',1,'batch','DEVELOPMENT'); INSERT INTO contents(id,brand_id,topic_id,idea_id,title,thesis,angle,master_hook,master_script,caption_base) VALUES('c','b','t','i','C','T','A','H','S','Caption'); INSERT INTO content_variants(id,content_id,platform,hook,script,title,caption) VALUES('v','c','TIKTOK','H','S','T','C'); INSERT INTO assets(id,content_variant_id,type,source,storage_location,mime_type,byte_size,original_filename,status) VALUES('a','v','video','upload','storage/a.mp4','video/mp4',12,'a.mp4','READY');"); assert.equal(db.prepare("SELECT status FROM ideas WHERE id='i'").get().status, "SELECTED"); assert.equal(db.prepare("SELECT count(*) count FROM content_variants").get().count, 1); assert.equal(db.prepare("SELECT status FROM assets").get().status, "READY"); });
test("social account, publication and idempotency are persistent", () => { const db = database(); db.exec("INSERT INTO ideas(id,topic_id,title,angle) VALUES('i','t','I','A'); INSERT INTO contents(id,brand_id,topic_id,idea_id,title,thesis,angle,master_hook,master_script) VALUES('c','b','t','i','C','T','A','H','S'); INSERT INTO content_variants(id,content_id,platform,hook,script,title,caption) VALUES('v','c','YOUTUBE_SHORTS','H','S','T','C'); INSERT INTO assets(id,content_variant_id,type,source,storage_location,status) VALUES('a','v','video','upload','storage/a.mp4','READY'); INSERT INTO social_accounts(id,brand_id,platform,username,display_name,connection_status) VALUES('sa','b','YOUTUBE_SHORTS','channel','Channel','CONNECTED'); INSERT INTO publications(id,content_variant_id,social_account_id,asset_id,provider,status,idempotency_key) VALUES('p','v','sa','a','YOUTUBE','PROCESSING','same-key');"); assert.throws(() => db.exec("INSERT INTO publications(id,content_variant_id,asset_id,provider,status,idempotency_key) VALUES('p2','v','a','YOUTUBE','QUEUED','same-key')"), /UNIQUE/); assert.equal(db.prepare("SELECT status FROM publications").get().status, "PROCESSING"); });
