import test from "node:test";
import assert from "node:assert/strict";
import { loadConfig, configurationHealth } from "../src/config.ts";
import { safeErrorMessage } from "../src/errors.ts";
import { DevelopmentAIProvider } from "../src/ai/provider.ts";
import { OpenAIProvider } from "../src/ai/openai-provider.ts";

test("config normalizes safe defaults without requiring OPENAI_MODEL",()=>{const c=loadConfig({});assert.equal(c.OPENAI_MODEL,"gpt-5-mini");assert.equal(c.OPENAI_TIMEOUT_MS,45000);assert.equal(c.AI_PROVIDER,"disabled")});
test("health never exposes secret values and reports missing Pexels",()=>{const h=configurationHealth(loadConfig({ASSET_PROVIDER:"pexels",PEXELS_API_KEY:""}));assert.equal(h.ASSET_PROVIDER.status,"ERROR");assert.doesNotMatch(JSON.stringify(h),/API_KEY|secret/i)});
test("disabled asset provider is explicitly not configured",()=>{const h=configurationHealth(loadConfig({ASSET_PROVIDER:"disabled"}));assert.equal(h.ASSET_PROVIDER.status,"NOT_CONFIGURED")});
test("template, voice and Creatomate readiness require official local config",()=>{const h=configurationHealth(loadConfig({CREATOMATE_TEMPLATE_CONTRACT:"dark-media-composer-v1",CREATOMATE_TEMPLATE_ID:"template",CREATOMATE_API_KEY:"key",CREATOMATE_VOICE_ID:"voice"}));assert.equal(h.CREATOMATE.status,"OK");assert.equal(h.CREATOMATE_TEMPLATE.status,"OK");assert.equal(h.ELEVENLABS_VOICE.status,"OK")});
test("development RenderPlan takes voice only from CREATOMATE_VOICE_ID",async()=>{const old=process.env.CREATOMATE_VOICE_ID;process.env.CREATOMATE_VOICE_ID="editorial-voice";try{const provider=new DevelopmentAIProvider();const content={title:"t",thesis:"t",hook:"h",script:"s",caption:"c",cta:"x",hashtags:[],estimatedDuration:30,factualClaims:[],sourceReferences:[],warnings:[],scenes:Array.from({length:6},(_,i)=>({order:i+1,startSeconds:i*5,durationSeconds:5,visualType:"TEXT_CARD",assetQuery:"",narration:"texto curto",caption:"texto",captionPosition:"CENTER",mediaFit:"COVER",mediaMotion:"NONE",transition:"CUT"}))};const plan=await provider.generateRenderPlan(content,[],{name:"Brand"});assert.equal(plan.voice.voiceId,"editorial-voice")}finally{if(old===undefined)delete process.env.CREATOMATE_VOICE_ID;else process.env.CREATOMATE_VOICE_ID=old}});
test("OpenAI timeout and network errors retain safe distinct codes",async()=>{const old=process.env.OPENAI_TIMEOUT_MS;process.env.OPENAI_TIMEOUT_MS="1";const timeout=new OpenAIProvider("key","model",(_u,{signal})=>new Promise((_r,reject)=>signal.addEventListener("abort",()=>reject(new DOMException("aborted","AbortError")),{once:true})));try{await assert.rejects(timeout.generateIdeaCandidates({}),e=>e.code==="OPENAI_TIMEOUT")}finally{if(old===undefined)delete process.env.OPENAI_TIMEOUT_MS;else process.env.OPENAI_TIMEOUT_MS=old}const network=new OpenAIProvider("key","model",async()=>{throw new TypeError("secret network detail")});await assert.rejects(network.generateIdeaCandidates({}),e=>e.code==="OPENAI_NETWORK_ERROR"&&!e.message.includes("secret"))});
test("safe UI errors are specific",()=>{assert.equal(safeErrorMessage("OPENAI_TIMEOUT"),"A OpenAI excedeu o tempo limite.");assert.equal(safeErrorMessage("OPENAI_SCHEMA_INVALID"),"A resposta da IA não passou pela validação.")});
