import { integrationState } from "@/src/social/connections";
export const dynamic = "force-dynamic";

const soon = [{ name: "Instagram", detail: "Provider preservado para fase futura." }, { name: "Facebook", detail: "Provider preservado para fase futura." }, { name: "Kwai", detail: "Provider próprio previsto; não será tratado como TikTok." }];
export default async function Integrations({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const query = await searchParams, tiktok = integrationState("TIKTOK"), youtube = integrationState("YOUTUBE");
  return <div className="page"><div className="titleRow"><div><div className="eyebrow">CANAIS OFICIAIS</div><h1>Integrações</h1></div><span className="tag">TOKENS SOMENTE NO BACKEND</span></div>
    {query.error && <div className="notice">Não foi possível concluir: <b>{query.error}</b>. Nenhuma conexão foi simulada.</div>}
    {query.connected && <div className="successNotice">{query.connected} conectado com sucesso pelo callback OAuth.</div>}
    <div className="integrationGrid"><Channel name="TikTok" state={tiktok} description="OAuth oficial e upload para inbox/revisão. O envio não é exibido como publicado." href="/api/oauth/tiktok/start" missing="TIKTOK_CLIENT_KEY, TIKTOK_CLIENT_SECRET, TIKTOK_REDIRECT_URI e TOKEN_ENCRYPTION_KEY"/><Channel name="YouTube" state={youtube} description="OAuth Google e upload resumable privado; permanece em processamento até confirmação do provider." href="/api/oauth/youtube/start" missing="GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI e TOKEN_ENCRYPTION_KEY"/>{soon.map(channel=><section className="panel integrationCard mutedCard" key={channel.name}><span className="channelMark">{channel.name.slice(0,2).toUpperCase()}</span><div><h2>{channel.name}</h2><span className="statusPill">EM BREVE</span><p>{channel.detail}</p><button disabled>NÃO DISPONÍVEL</button></div></section>)}</div>
    <div className="notice"><b>Localhost e OAuth:</b> o redirect URI cadastrado no console de cada provider deve coincidir exatamente com o `.env`. Use HTTPS/túnel somente quando exigido pelo provider e nunca compartilhe o banco ou `TOKEN_ENCRYPTION_KEY`.</div>
  </div>;
}
function Channel({ name, state, description, href, missing }: { name: string; state: ReturnType<typeof integrationState>; description: string; href: string; missing: string }) { return <section className="panel integrationCard"><span className="channelMark">{name.slice(0,2).toUpperCase()}</span><div><h2>{name}</h2><span className={`statusPill ${state.status === "CONNECTED" ? "connected" : ""}`}>{state.status}</span><p>{description}</p>{state.displayName && <p><b>{state.displayName}</b><small className="muted" style={{display:"block"}}>ID: {state.externalAccountId}</small></p>}{state.configured && state.status !== "CONNECTED" ? <a className="btn" href={href}>CONECTAR {name.toUpperCase()}</a> : state.status === "CONNECTED" ? <span className="good">CONTA CONECTADA</span> : <p className="configMissing">Faltam: {missing}</p>}</div></section>; }
