import type { RenderPlan } from "../ai/schemas.ts";
export type RenderStatus="RENDERING"|"RENDERED"|"FAILED";
export type RenderSubmission={externalId:string;status:"RENDERING";metadata:Record<string,unknown>};
export type RenderResult={externalId:string;status:RenderStatus;videoUrl?:string;errorCode?:string;errorDetail?:string;metadata:Record<string,unknown>};
export interface RenderProvider{readonly available:boolean;readonly name:string;submit(plan:RenderPlan):Promise<RenderSubmission>;status(externalId:string):Promise<RenderResult>}
export class RenderProviderError extends Error{code:string;constructor(code:string,message:string){super(message);this.code=code;this.name="RenderProviderError"}}
export class DisabledRenderProvider implements RenderProvider{readonly available=false;readonly name="RENDERIZAÇÃO NÃO CONFIGURADA";private fail():never{throw new RenderProviderError("RENDER_NOT_CONFIGURED",this.name)}async submit():Promise<RenderSubmission>{return this.fail()}async status():Promise<RenderResult>{return this.fail()}}
export class CreatomateProvider implements RenderProvider{readonly available=true;readonly name="Creatomate";private key:string;private templateId:string;private fetcher:typeof fetch;constructor(key:string,templateId:string,fetcher:typeof fetch=fetch){this.key=key;this.templateId=templateId;this.fetcher=fetcher}
 async submit(plan:RenderPlan){const response=await this.fetcher("https://api.creatomate.com/v1/renders",{method:"POST",headers:{Authorization:`Bearer ${this.key}`,"Content-Type":"application/json"},body:JSON.stringify({template_id:this.templateId,modifications:renderModifications(plan)})});if(!response.ok)throw new RenderProviderError("CREATOMATE_SUBMIT_FAILED",`Creatomate indisponível (${response.status})`);const body=await response.json() as Array<{id?:string}>|{id?:string};const item=Array.isArray(body)?body[0]:body;if(!item?.id)throw new RenderProviderError("CREATOMATE_INVALID_RESPONSE","Creatomate não retornou render ID");return {externalId:item.id,status:"RENDERING" as const,metadata:{templateId:this.templateId}}}
 async status(externalId:string){const response=await this.fetcher(`https://api.creatomate.com/v1/renders/${encodeURIComponent(externalId)}`,{headers:{Authorization:`Bearer ${this.key}`}});if(!response.ok)throw new RenderProviderError("CREATOMATE_STATUS_FAILED",`Consulta Creatomate falhou (${response.status})`);const b=await response.json() as {id?:string;status?:string;url?:string;error_message?:string};if(b.status==="succeeded"&&b.url)return {externalId,status:"RENDERED" as const,videoUrl:b.url,metadata:{providerStatus:b.status}};if(b.status==="failed")return {externalId,status:"FAILED" as const,errorCode:"CREATOMATE_RENDER_FAILED",errorDetail:b.error_message||"Render falhou",metadata:{providerStatus:b.status}};return {externalId,status:"RENDERING" as const,metadata:{providerStatus:b.status||"unknown"}}}
}
function renderModifications(plan:RenderPlan){const result:Record<string,string|number>={"Brand":plan.branding.brandName};plan.scenes.forEach((s,i)=>{result[`Scene-${i+1}.Text`]=s.text;result[`Scene-${i+1}.VoiceOver`]=s.voiceOverText;result[`Scene-${i+1}.Duration`]=s.durationSeconds;result[`Scene-${i+1}.AssetQuery`]=s.assetQuery});return result}
export function getRenderProvider():RenderProvider{return process.env.CREATOMATE_API_KEY&&process.env.CREATOMATE_TEMPLATE_ID?new CreatomateProvider(process.env.CREATOMATE_API_KEY,process.env.CREATOMATE_TEMPLATE_ID):new DisabledRenderProvider()}
