"use server";
import { db } from "@/src/db"; import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation";
const id=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`; const val=(f:FormData,k:string)=>String(f.get(k)??"").trim();
export async function updateBrand(f:FormData){db().prepare(`UPDATE brands SET name=?,niche=?,target_audience=?,persona=?,tone=?,editorial_aggressiveness=?,controversy_appetite=?,preferred_topics=?,avoided_topics=?,preferred_vocabulary=?,avoided_vocabulary=?,cta_preferences=?,content_objectives=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...["name","niche","targetAudience","persona","tone","aggressiveness","controversy","preferredTopics","avoidedTopics","preferredVocabulary","avoidedVocabulary","cta","objectives"].map(k=>val(f,k)),val(f,"id"));revalidatePath("/brands");}
export async function addSource(f:FormData){db().prepare('INSERT INTO sources(id,brand_id,name,type,url,enabled,priority,reliability,category) VALUES(?,?,?,?,?,1,?,?,?)').run(id('src'),val(f,'brandId'),val(f,'name'),val(f,'type'),val(f,'url'),Number(val(f,'priority')),Number(val(f,'reliability')),val(f,'category'));revalidatePath('/sources');}
export async function toggleSource(f:FormData){db().prepare('UPDATE sources SET enabled=CASE enabled WHEN 1 THEN 0 ELSE 1 END WHERE id=?').run(val(f,'id'));revalidatePath('/sources');}
export async function addSourceItem(f:FormData){db().prepare('INSERT INTO source_items(id,source_id,title,url,published_at,summary,processing_status,provenance_group) VALUES(?,?,?,?,?,?,?,?)').run(id('item'),val(f,'sourceId'),val(f,'title'),val(f,'url'),val(f,'publishedAt')||null,val(f,'summary'),'NEW',val(f,'provenance')||null);revalidatePath('/sources');}
export async function addIdea(f:FormData){const newId=id('idea');db().prepare('INSERT INTO ideas(id,topic_id,title,angle,rationale,rank_score,status) VALUES(?,?,?,?,?,0,?)').run(newId,val(f,'topicId'),val(f,'title'),val(f,'angle'),val(f,'rationale'),'DRAFT');redirect(`/studio?idea=${newId}`);}
export async function saveContent(f:FormData){const contentId=val(f,'contentId')||id('content'), existing=db().prepare('SELECT id FROM contents WHERE id=?').get(contentId);if(existing)db().prepare('UPDATE contents SET title=?,thesis=?,angle=?,master_hook=?,master_script=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(val(f,'title'),val(f,'thesis'),val(f,'angle'),val(f,'hook'),val(f,'script'),val(f,'status'),contentId);else db().prepare('INSERT INTO contents(id,brand_id,topic_id,idea_id,title,thesis,angle,master_hook,master_script,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(contentId,val(f,'brandId'),val(f,'topicId'),val(f,'ideaId'),val(f,'title'),val(f,'thesis'),val(f,'angle'),val(f,'hook'),val(f,'script'),'DRAFT');revalidatePath('/studio');redirect(`/studio?content=${contentId}`);}
export async function feedback(f:FormData){const status=val(f,'action')==='approved'?'APPROVED':val(f,'action')==='rejected'?'REJECTED':'DRAFT';db().prepare('UPDATE contents SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,val(f,'contentId'));db().prepare('INSERT INTO editorial_feedback(id,content_id,action,reason,note) VALUES(?,?,?,?,?)').run(id('feedback'),val(f,'contentId'),val(f,'action'),val(f,'reason')||null,val(f,'note')||null);revalidatePath('/studio');}
export async function saveVariant(f:FormData){db().prepare('UPDATE content_variants SET hook=?,script=?,title=?,caption=?,hashtags=?,cta=?,target_duration=?,visual_direction=? WHERE id=?').run(val(f,'hook'),val(f,'script'),val(f,'title'),val(f,'caption'),val(f,'hashtags'),val(f,'cta'),Number(val(f,'duration'))||null,val(f,'visual'),val(f,'id'));revalidatePath('/studio');}
export async function schedulePublication(f:FormData){db().prepare('INSERT INTO publications(id,content_variant_id,social_account_id,scheduled_for,status) VALUES(?,?,?,?,?)').run(id('pub'),val(f,'variantId'),val(f,'accountId')||null,new Date(val(f,'scheduledFor')).toISOString(),'SCHEDULED');revalidatePath('/calendar');}
