import { all,one,Row } from "@/src/db";
import Link from "next/link";
export const dynamic="force-dynamic";

const stages=["Sources","Topics","Ideas","Master","Variants","RenderPlan","Creatomate","Rendered","Review","Approved","Publication"];
export default function Dashboard(){
  const counts=one<Row>(`SELECT (SELECT count(*) FROM source_items) sources,(SELECT count(*) FROM topics) topics,(SELECT count(*) FROM ideas) ideas,(SELECT count(*) FROM contents) contents,(SELECT count(*) FROM renders WHERE status='RENDERED') rendered,(SELECT count(*) FROM contents WHERE status='REVIEW') review,(SELECT count(*) FROM contents WHERE status='APPROVED') approved,(SELECT count(*) FROM publications) publications,(SELECT count(*) FROM publications WHERE status='FAILED') failed`)!;
  const hot=all<Row>(`SELECT * FROM topics ORDER BY editorial_priority_score DESC LIMIT 5`);
  const metrics=[["Ideias geradas",counts.ideas,"✦"],["Conteúdos criados",counts.contents,"▤"],["Vídeos renderizados",counts.rendered,"▶"],["Publicações",counts.publications,"↗"],["Aguardando revisão",counts.review,"◉"],["Aprovados",counts.approved,"✓"]];
  const activeIndex=Number(counts.approved)>0?9:Number(counts.rendered)>0?7:Number(counts.contents)>0?5:Number(counts.ideas)>0?2:Number(counts.topics)>0?1:0;
  return <div className="page">
    <div className="titleRow"><div><div className="eyebrow">CENTRO DE OPERAÇÕES</div><h1>Dashboard</h1><p className="subtitle">Visão geral do seu motor de conteúdo</p></div><Link className="btn" href="/hot-queue">✦ EXPLORAR OPORTUNIDADES</Link></div>
    <div className="dashboardMetrics">{metrics.map(([label,value,icon])=><section className="panel stat" key={String(label)}><div className="metricIcon">{icon}</div><small>{label}</small><b>{value}</b><span className="statMeta">Dados persistidos</span></section>)}</div>
    <section className="panel pipeline"><div className="pipelineStep active"><span className="pipelineDot">AI</span><b>PIPELINE</b></div>{stages.map((stage,index)=><div className={`pipelineStep ${index<=activeIndex?"active":""}`} key={stage}><span className="pipelineDot">{index<activeIndex?"✓":index+1}</span><b>{stage}</b></div>)}</section>
    <div className="grid"><section className="panel span8"><div className="eyebrow">HOT NOW</div><h2>Oportunidades editoriais em destaque</h2><table><thead><tr><th>Topic</th><th>Freshness</th><th>Viralidade</th><th>Confiança</th><th>Prioridade</th></tr></thead><tbody>{hot.map(t=><tr key={String(t.id)}><td><div className="topicTitle">{t.title}</div><small className="muted">{t.status}</small></td><td><span className="statusPill">{t.freshness}</span></td><td><span className="score hot">{t.virality_score}</span></td><td><span className="score good">{t.confidence_score}</span></td><td><span className="priority">{t.editorial_priority_score}</span></td></tr>)}</tbody></table><div className="actions"><Link className="btn secondary" href="/hot-queue">VER HOT QUEUE COMPLETA →</Link></div></section>
    <section className="panel span4"><div className="eyebrow">DECISÃO HUMANA</div><h2>Seu foco agora</h2><p className="muted">A máquina pesquisa, propõe e produz. Você revisa apenas as decisões que importam.</p><div className="flow"><b>REVISAR</b> → <b>ESCOLHER</b> → <b>APROVAR</b></div><p><b>{counts.review} conteúdo(s)</b><br/><span className="muted">aguardando revisão editorial.</span></p><Link href="/studio" className="btn">ABRIR CONTENT STUDIO</Link><hr/><p className="muted"><b className="good">{counts.sources}</b> itens de fontes alimentam o motor. Falhas de publicação: <b className={Number(counts.failed)>0?"uncertain":"good"}>{counts.failed}</b>.</p></section></div>
  </div>;
}
