import { ideaCandidateSchema, masterContentSchema, platformVariantSchema, renderPlanSchema, type IdeaCandidate, type MasterContent, type PlatformVariant, type RenderPlan } from "./schemas.ts";
import { OpenAIProvider } from "./openai-provider.ts";

export type TopicContext = { id:string; title:string; summary:string; category:string; confidenceScore:number; viralityScore:number; momentumScore:number; saturationRisk:number; freshness:string; factualStatus:string; corroborationScore:number; signals:string[]; sourceItems:Array<{id:string;title:string;summary:string;url:string|null;publishedAt:string|null;sourceName:string;reliability:number;dependsOnSourceId:string|null}>; brand:{id:string;name:string;tone:string;targetAudience:string;editorialAggressiveness:string} };
export type AIUsage = { operation:string; model:string; inputTokens:number; outputTokens:number; estimatedCostUsd:number };
export interface AIProvider { readonly available:boolean; readonly name:string; readonly provenanceLabel:"AI"|"DEVELOPMENT"|"DISABLED"; lastUsage?:AIUsage; generateIdeaCandidates(topic:TopicContext,generation?:number):Promise<IdeaCandidate[]>; rankIdeaCandidates(candidates:IdeaCandidate[],topic:TopicContext):Promise<IdeaCandidate[]>; generateContentFromIdea(topic:TopicContext,idea:IdeaCandidate):Promise<MasterContent>; generatePlatformVariants(content:MasterContent):Promise<PlatformVariant[]>; generateRenderPlan(content:MasterContent,variants:PlatformVariant[],brand:TopicContext["brand"]):Promise<RenderPlan>; }
export class AIUnavailableError extends Error { constructor(){super("IA NÃO CONFIGURADA");this.name="AIUnavailableError";} }
export class DisabledAIProvider implements AIProvider { readonly available=false;readonly name="IA não configurada";readonly provenanceLabel="DISABLED" as const;private fail():never{throw new AIUnavailableError()} async generateIdeaCandidates():Promise<IdeaCandidate[]>{return this.fail()} async rankIdeaCandidates():Promise<IdeaCandidate[]>{return this.fail()} async generateContentFromIdea():Promise<MasterContent>{return this.fail()} async generatePlatformVariants():Promise<PlatformVariant[]>{return this.fail()} async generateRenderPlan():Promise<RenderPlan>{return this.fail()} }

export class DevelopmentAIProvider implements AIProvider {
 readonly available=true;readonly name="Provider determinístico de desenvolvimento";readonly provenanceLabel="DEVELOPMENT" as const;
 async generateIdeaCandidates(t:TopicContext,generation=0){const uncertain=t.confidenceScore<50,w=uncertain?["CONFIRMAÇÃO BAIXA — preserve linguagem de rumor."]:[],claims=t.sourceItems.map(s=>({text:s.summary,confidence:(t.confidenceScore>=80?"HIGH":t.confidenceScore>=50?"MEDIUM":"LOW") as "HIGH"|"MEDIUM"|"LOW",sourceItemIds:[s.id]})),refs=t.sourceItems.map(s=>s.id),facts=t.sourceItems.map(s=>s.summary).slice(0,3),q=uncertain?"Rumor sobre":"A resposta em",shift=generation%3;return [
  {title:`${q} ${t.title} ganha força`,angle:"A informação nova e suas consequências verificáveis.",rationale:"Prioriza momentum sem extrapolar as fontes.",suggestedHook:uncertain?"O rumor ganhou força — mas o que está confirmado?":"Uma informação mudou o rumo desta história.",viralityPotential:t.viralityScore,editorialStrategy:"NOVIDADE + CONSEQUÊNCIA",supportingFacts:facts,factualClaims:claims,sourceReferences:refs,warnings:w,recommendedCandidate:true},
  {title:`Como começou ${t.title.toLowerCase()}`,angle:"Cronologia dos fatos disponíveis.",rationale:"Dá contexto factual e reduz repetição.",suggestedHook:"Todo mundo viu o desfecho, mas tudo começou aqui.",viralityPotential:Math.max(0,t.viralityScore-5+shift),editorialStrategy:"CRONOLOGIA + CONTEXTO",supportingFacts:facts,factualClaims:claims,sourceReferences:refs,warnings:w,recommendedCandidate:false},
  {title:`Por que ${t.title.toLowerCase()} dividiu reações`,angle:"Reações observáveis e pontos de debate.",rationale:"Estimula conversa sem atribuir intenções.",suggestedHook:"A reação se dividiu por causa deste ponto.",viralityPotential:Math.max(0,t.viralityScore-9+shift),editorialStrategy:"REAÇÃO + DEBATE",supportingFacts:facts,factualClaims:claims,sourceReferences:refs,warnings:w,recommendedCandidate:false}
 ].map(x=>ideaCandidateSchema.parse(x))}
 async rankIdeaCandidates(c:IdeaCandidate[]){return [...c].sort((a,b)=>b.viralityPotential-a.viralityPotential).map((x,i)=>({...x,recommendedCandidate:i===0}))}
 async generateContentFromIdea(t:TopicContext,i:IdeaCandidate){const lines=[i.suggestedHook,t.summary,"O contexto muda a leitura desta história.","As fontes disponíveis sustentam estes pontos.","Ainda há detalhes em desenvolvimento.","Acompanhe as atualizações e confira as fontes.","O que isso muda daqui para frente?","Qual é a sua leitura?"];const durations=[4,5,5,5,5,5,5,6],types=["STOCK_VIDEO","STOCK_IMAGE","TEXT_CARD","STOCK_VIDEO","STOCK_IMAGE","TEXT_CARD","STOCK_VIDEO","BRAND_CARD"] as const;let start=0;const scenes=lines.map((line,index)=>{const durationSeconds=durations[index],visualType=types[index];const scene={order:index+1,startSeconds:start,durationSeconds,visualType,assetQuery:visualType.startsWith("STOCK")?`${t.title} ${index+1}`:"",narration:line,headline:index===0?i.suggestedHook:index===7?"Radar Pop":undefined,caption:line.slice(0,180),captionPosition:index===0?"CENTER" as const:"BOTTOM" as const,mediaFit:"COVER" as const,mediaMotion:visualType==="STOCK_IMAGE"?"SLOW_ZOOM_IN" as const:"NONE" as const,transition:index%3===0?"FADE" as const:"CUT" as const,textStyle:"EDITORIAL",emphasisWords:[],overlay:{enabled:visualType.startsWith("STOCK"),opacity:.2}};start+=durationSeconds;return scene});return masterContentSchema.parse({title:i.title,thesis:i.angle,hook:i.suggestedHook,script:lines.join("\n\n"),caption:`${i.title}. Contexto baseado nas fontes vinculadas.`,cta:"Qual é a sua leitura?",hashtags:["#RadarPop","#CulturaPop"],estimatedDuration:40,factualClaims:i.factualClaims,sourceReferences:i.sourceReferences,warnings:i.warnings,scenes})}
 async generatePlatformVariants(c:MasterContent){return [{platform:"TIKTOK" as const,title:c.title,hook:c.hook,script:c.script,caption:c.caption,description:"",cta:c.cta,hashtags:c.hashtags,targetDuration:c.estimatedDuration},{platform:"YOUTUBE_SHORTS" as const,title:c.title.slice(0,100),hook:`Entenda: ${c.hook}`,script:c.script,caption:"",description:c.caption,cta:"Inscreva-se para acompanhar.",hashtags:["#Shorts",...c.hashtags],targetDuration:c.estimatedDuration}].map(x=>platformVariantSchema.parse(x))}
 async generateRenderPlan(c:MasterContent,_v:PlatformVariant[],b:TopicContext["brand"]){return renderPlanSchema.parse({version:"dark-media-composer-v1",aspectRatio:"9:16",targetDuration:c.estimatedDuration,scenes:c.scenes,voice:{provider:"ELEVENLABS",voiceId:process.env.ELEVENLABS_VOICE_ID||"template-default-voice"},backgroundAudio:{mood:"editorial",volume:.18,sourceUrl:null,ducking:true},branding:{brandName:b.name,primaryColor:"#D7FF54",fontFamily:"Inter",logoAssetUrl:null}})}
}
export function getAIProvider():AIProvider { if(process.env.AI_PROVIDER==="development")return new DevelopmentAIProvider(); if(process.env.AI_PROVIDER==="openai"&&process.env.OPENAI_API_KEY)return new OpenAIProvider(process.env.OPENAI_API_KEY); return new DisabledAIProvider(); }
export type { IdeaCandidate, MasterContent, PlatformVariant, RenderPlan } from "./schemas.ts";
