import { ideaCandidateSchema, masterContentSchema, platformVariantSchema, renderPlanSchema, type IdeaCandidate, type MasterContent, type PlatformVariant, type RenderPlan } from "./schemas.ts";
import { OpenAIProvider } from "./openai-provider.ts";

export type TopicContext = { id:string; title:string; summary:string; category:string; confidenceScore:number; viralityScore:number; momentumScore:number; saturationRisk:number; freshness:string; factualStatus:string; corroborationScore:number; signals:string[]; sourceItems:Array<{id:string;title:string;summary:string;url:string|null;publishedAt:string|null;sourceName:string;reliability:number;dependsOnSourceId:string|null}>; brand:{id:string;name:string;tone:string;targetAudience:string;editorialAggressiveness:string} };
export type AIUsage = { operation:string; model:string; inputTokens:number; outputTokens:number; estimatedCostUsd:number };
export interface AIProvider { readonly available:boolean; readonly name:string; readonly provenanceLabel:"AI"|"DEVELOPMENT"|"DISABLED"; lastUsage?:AIUsage; generateIdeaCandidates(topic:TopicContext,generation?:number):Promise<IdeaCandidate[]>; rankIdeaCandidates(candidates:IdeaCandidate[],topic:TopicContext):Promise<IdeaCandidate[]>; generateContentFromIdea(topic:TopicContext,idea:IdeaCandidate):Promise<MasterContent>; generatePlatformVariants(content:MasterContent):Promise<PlatformVariant[]>; generateRenderPlan(content:MasterContent,variants:PlatformVariant[],brand:TopicContext["brand"]):Promise<RenderPlan>; }
export class AIUnavailableError extends Error { constructor(){super("IA NÃO CONFIGURADA");this.name="AIUnavailableError";} }
export class DisabledAIProvider implements AIProvider { readonly available=false;readonly name="IA não configurada";readonly provenanceLabel="DISABLED" as const;private fail():never{throw new AIUnavailableError()} async generateIdeaCandidates():Promise<IdeaCandidate[]>{return this.fail()} async rankIdeaCandidates():Promise<IdeaCandidate[]>{return this.fail()} async generateContentFromIdea():Promise<MasterContent>{return this.fail()} async generatePlatformVariants():Promise<PlatformVariant[]>{return this.fail()} async generateRenderPlan():Promise<RenderPlan>{return this.fail()} }

export class DevelopmentAIProvider implements AIProvider {
 readonly available=true;readonly name="Provider determinístico de desenvolvimento";readonly provenanceLabel="DEVELOPMENT" as const;
 async generateIdeaCandidates(t:TopicContext,generation=0){const uncertain=t.confidenceScore<50,w=uncertain?["CONFIRMAÇÃO BAIXA — preserve linguagem de rumor."]:[],claims=t.sourceItems.map(s=>({text:s.summary,confidence:(t.confidenceScore>=80?"HIGH":t.confidenceScore>=50?"MEDIUM":"LOW") as "HIGH"|"MEDIUM"|"LOW",sourceItemIds:[s.id]})),refs=t.sourceItems.map(s=>s.id),facts=t.sourceItems.map(s=>s.summary).slice(0,3),q=uncertain?"Rumor sobre":"A resposta em",shift=generation%3;return [
  {title:`${q} ${t.title} ganha força`,angle:"A informação nova e suas consequências verificáveis.",rationale:"Prioriza momentum sem extrapolar as fontes.",suggestedHook:uncertain?"O rumor ganhou força — mas o que está confirmado?":"Uma informação mudou o rumo desta história.",viralityPotential:t.viralityScore,editorialStrategy:"NOVIDADE + CONSEQUÊNCIA",supportingFacts:facts,factualClaims:claims,sourceReferences:refs,warnings:w,recommendedCandidate:true},
  {title:`Como começou ${t.title.toLowerCase()}`,angle:"Cronologia dos fatos disponíveis.",rationale:"Dá contexto factual e reduz repetição.",suggestedHook:"Todo mundo viu o desfecho, mas tudo começou aqui.",viralityPotential:Math.max(0,t.viralityScore-5+shift),editorialStrategy:"CRONOLOGIA + CONTEXTO",supportingFacts:facts,factualClaims:claims,sourceReferences:refs,warnings:w,recommendedCandidate:false},
  {title:`Por que ${t.title.toLowerCase()} dividiu reações`,angle:"Reações observáveis e pontos de debate.",rationale:"Estimula conversa sem atribuir intenções.",suggestedHook:"A reação se dividiu por causa deste ponto.",viralityPotential:Math.max(0,t.viralityScore-9+shift),editorialStrategy:"REAÇÃO + DEBATE",supportingFacts:facts,factualClaims:claims,sourceReferences:refs,warnings:w,recommendedCandidate:false}
 ].map(x=>ideaCandidateSchema.parse(x))}
 async rankIdeaCandidates(c:IdeaCandidate[]){return [...c].sort((a,b)=>b.viralityPotential-a.viralityPotential).map((x,i)=>({...x,recommendedCandidate:i===0}))}
 async generateContentFromIdea(t:TopicContext,i:IdeaCandidate){const scenes=[{order:1,text:i.suggestedHook,durationSeconds:5,visualType:"TEXT" as const,assetQuery:t.title,caption:i.suggestedHook,captionPosition:"CENTER" as const,transition:"cut",voiceOverText:i.suggestedHook},{order:2,text:t.summary,durationSeconds:25,visualType:"SOURCE_MEDIA" as const,assetQuery:t.sourceItems[0]?.title??t.title,caption:t.summary,captionPosition:"BOTTOM" as const,transition:"cut",voiceOverText:t.summary},{order:3,text:"Confira as fontes e forme sua leitura.",durationSeconds:10,visualType:"BRAND" as const,assetQuery:"",caption:"Qual é a sua leitura?",captionPosition:"CENTER" as const,transition:"fade",voiceOverText:"Confira as fontes e forme sua leitura."}];return masterContentSchema.parse({title:i.title,thesis:i.angle,hook:i.suggestedHook,script:`${i.suggestedHook}\n\n${t.summary}\n\nConfira as fontes e forme sua leitura.`,caption:`${i.title}. Contexto baseado nas fontes vinculadas.`,cta:"Qual é a sua leitura?",hashtags:["#RadarPop","#CulturaPop"],estimatedDuration:40,factualClaims:i.factualClaims,sourceReferences:i.sourceReferences,warnings:i.warnings,scenes})}
 async generatePlatformVariants(c:MasterContent){return [{platform:"TIKTOK" as const,title:c.title,hook:c.hook,script:c.script,caption:c.caption,description:"",cta:c.cta,hashtags:c.hashtags,targetDuration:c.estimatedDuration},{platform:"YOUTUBE_SHORTS" as const,title:c.title.slice(0,100),hook:`Entenda: ${c.hook}`,script:c.script,caption:"",description:c.caption,cta:"Inscreva-se para acompanhar.",hashtags:["#Shorts",...c.hashtags],targetDuration:c.estimatedDuration}].map(x=>platformVariantSchema.parse(x))}
 async generateRenderPlan(c:MasterContent,_v:PlatformVariant[],b:TopicContext["brand"]){return renderPlanSchema.parse({aspectRatio:"9:16",targetDuration:c.estimatedDuration,scenes:c.scenes,backgroundAudio:{mood:"editorial",volume:.18},branding:{brandName:b.name,primaryColor:"#d7ff54",fontFamily:"Inter",logoAssetUrl:null}})}
}
export function getAIProvider():AIProvider { if(process.env.AI_PROVIDER==="development")return new DevelopmentAIProvider(); if(process.env.AI_PROVIDER==="openai"&&process.env.OPENAI_API_KEY)return new OpenAIProvider(process.env.OPENAI_API_KEY); return new DisabledAIProvider(); }
export type { IdeaCandidate, MasterContent, PlatformVariant, RenderPlan } from "./schemas.ts";
