import { all, db, one, type Row } from "../db.ts";
import { getAIProvider, type IdeaCandidate, type MasterContent, type TopicContext } from "./provider.ts";
import { ideaCandidateSchema, masterContentSchema, platformVariantSchema, renderPlanSchema } from "./schemas.ts";
import { resolveRenderPlanAssets } from "../assets/resolution.ts";
const newId=(p:string)=>`${p}-${crypto.randomUUID()}`,json=JSON.stringify;
type IdeaSelectionStage = "start"|"topic-loaded"|"candidate-validated"|"master-content"|"variants"|"render-plan"|"persistence"|"asset-resolution";
const safeMessage = (error: unknown) => {
  const code = error && typeof error === "object" && "code" in error ? String(error.code) : error instanceof Error ? error.message : "UNKNOWN_ERROR";
  return /^[A-Z0-9_]+$/.test(code) ? code : "UNEXPECTED_ERROR";
};
const logSelection = (message: string) => console.info(`[idea-select] ${message}`);
export function loadTopicContext(topicId:string):TopicContext{const t=one<Row>(`SELECT t.*,b.name brand_name,b.tone brand_tone,b.target_audience,b.editorial_aggressiveness FROM topics t JOIN brands b ON b.id=t.brand_id WHERE t.id=?`,topicId);if(!t)throw new Error("TOPIC_NOT_FOUND");const sources=all<Row>(`SELECT i.id,i.title,i.summary,i.url,i.published_at,i.depends_on_source_id,s.name source_name,s.reliability FROM source_items i JOIN sources s ON s.id=i.source_id JOIN topic_source_items x ON x.source_item_id=i.id WHERE x.topic_id=? ORDER BY x.is_primary DESC,i.discovered_at DESC LIMIT 12`,topicId);return{id:String(t.id),title:String(t.title),summary:String(t.summary),category:String(t.category),confidenceScore:Number(t.confidence_score),viralityScore:Number(t.virality_score),momentumScore:Number(t.momentum_score),saturationRisk:Number(t.saturation_risk),freshness:String(t.freshness),factualStatus:String(t.factual_status??"DEVELOPING"),corroborationScore:Number(t.corroboration_score??0),signals:String(t.signals).split(",").filter(Boolean),sourceItems:sources.map(s=>({id:String(s.id),title:String(s.title),summary:String(s.summary).slice(0,2000),url:s.url?String(s.url):null,publishedAt:s.published_at?String(s.published_at):null,sourceName:String(s.source_name),reliability:Number(s.reliability),dependsOnSourceId:s.depends_on_source_id?String(s.depends_on_source_id):null})),brand:{id:String(t.brand_id),name:String(t.brand_name),tone:String(t.brand_tone),targetAudience:String(t.target_audience),editorialAggressiveness:String(t.editorial_aggressiveness)}}}
function usage(provider:ReturnType<typeof getAIProvider>,operation:string,topicId?:string,contentId?:string,error?:unknown){const u=provider.lastUsage;db().prepare(`INSERT INTO ai_executions(id,content_id,topic_id,operation,provider,model,status,input_tokens,output_tokens,estimated_cost_usd,error_code) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(newId("ai"),contentId||null,topicId||null,operation,provider.name,u?.model||provider.name,error?"FAILED":"SUCCEEDED",u?.inputTokens||0,u?.outputTokens||0,u?.estimatedCostUsd||0,error?(error as {code?:string}).code||"AI_ERROR":null)}
export async function generateAndPersistCandidates(topicId:string,generation=0){const p=getAIProvider();if(!p.available)throw new Error("AI_NOT_CONFIGURED");const topic=loadTopicContext(topicId);try{const generated=(await p.generateIdeaCandidates(topic,generation)).map(x=>ideaCandidateSchema.parse(x));generated.forEach(candidate=>validateSources(candidate.factualClaims,candidate.sourceReferences,topic));usage(p,"GENERATE_IDEAS",topicId);const ranked=(await p.rankIdeaCandidates(generated,topic)).map(x=>ideaCandidateSchema.parse(x));usage(p,"RANK_IDEAS",topicId);if(ranked.length!==3||ranked.filter(x=>x.recommendedCandidate).length!==1)throw new Error("AI_CANDIDATE_COUNT_INVALID");const batch=newId("batch"),insert=db().prepare(`INSERT INTO ideas(id,topic_id,title,angle,rationale,rank_score,status,suggested_hook,editorial_strategy,supporting_facts,warnings,recommended,generation_batch_id,generated_by,factual_claims,source_references) VALUES(?,?,?,?,?,?,'CANDIDATE',?,?,?,?,?,?,?,?,?)`);db().exec("BEGIN IMMEDIATE");try{ranked.forEach(c=>insert.run(newId("idea"),topicId,c.title,c.angle,c.rationale,c.viralityPotential,c.suggestedHook,c.editorialStrategy,json(c.supportingFacts),json(c.warnings),c.recommendedCandidate?1:0,batch,p.provenanceLabel,json(c.factualClaims),json(c.sourceReferences)));db().exec("COMMIT")}catch(e){db().exec("ROLLBACK");throw e}return batch}catch(e){usage(p,"GENERATE_IDEAS",topicId,undefined,e);throw e}}
export function candidateFromRow(r:Row):IdeaCandidate{return ideaCandidateSchema.parse({title:r.title,angle:r.angle,rationale:r.rationale,suggestedHook:r.suggested_hook,viralityPotential:Number(r.rank_score),editorialStrategy:r.editorial_strategy,supportingFacts:JSON.parse(String(r.supporting_facts)),factualClaims:JSON.parse(String(r.factual_claims||"[]")),sourceReferences:JSON.parse(String(r.source_references||"[]")),warnings:JSON.parse(String(r.warnings)),recommendedCandidate:Boolean(r.recommended)})}
export async function generateContentForIdea(ideaId:string){
  const startedAt=Date.now();let stage:IdeaSelectionStage="start";let topicId:string|undefined;const p=getAIProvider();
  logSelection(`start idea=${ideaId}`);
  try{
    const existing=one<Row>("SELECT id FROM contents WHERE idea_id=? ORDER BY created_at LIMIT 1",ideaId);
    if(existing){logSelection(`idempotent-hit content=${existing.id} duration=${Date.now()-startedAt}ms`);return String(existing.id)}
    const idea=one<Row>("SELECT * FROM ideas WHERE id=?",ideaId);if(!idea)throw new Error("IDEA_NOT_FOUND");
    topicId=String(idea.topic_id);const topic=loadTopicContext(topicId);stage="topic-loaded";logSelection(`topic loaded duration=${Date.now()-startedAt}ms`);
    const candidate=candidateFromRow(idea);stage="candidate-validated";logSelection(`candidate validated duration=${Date.now()-startedAt}ms`);
    if(!p.available)throw new Error("AI_NOT_CONFIGURED");

    stage="master-content";let step=Date.now();logSelection("master content generation started");
    const draft=masterContentSchema.parse(await p.generateContentFromIdea(topic,candidate));validateSources(draft.factualClaims,draft.sourceReferences,topic);usage(p,"GENERATE_CONTENT",topic.id);logSelection(`master content generation completed duration=${Date.now()-step}ms`);
    stage="variants";step=Date.now();
    const variants=(await p.generatePlatformVariants(draft)).map(x=>platformVariantSchema.parse(x));usage(p,"GENERATE_VARIANTS",topic.id);logSelection(`variants generation completed duration=${Date.now()-step}ms`);
    stage="render-plan";step=Date.now();
    const plan=renderPlanSchema.parse(await p.generateRenderPlan(draft,variants,topic.brand));usage(p,"GENERATE_RENDER_PLAN",topic.id);logSelection(`render plan completed duration=${Date.now()-step}ms`);

    stage="persistence";step=Date.now();const contentId=newId("content"),planId=newId("plan");let persistedContentId=contentId;let persistedPlanId=planId;
    db().exec("BEGIN IMMEDIATE");
    try{
      // A second submission may have completed while this request was waiting for AI.
      const concurrent=one<Row>("SELECT id FROM contents WHERE idea_id=? ORDER BY created_at LIMIT 1",ideaId);
      if(concurrent){persistedContentId=String(concurrent.id);persistedPlanId=""}
      else{
        db().prepare(`INSERT INTO contents(id,brand_id,topic_id,idea_id,title,thesis,angle,master_hook,master_script,status,caption_base,cta,hashtags,estimated_duration,warnings,scenes) VALUES(?,?,?,?,?,?,?,?,?,'NEEDS_MEDIA',?,?,?,?,?,?)`).run(contentId,topic.brand.id,topic.id,ideaId,draft.title,draft.thesis,String(idea.angle),draft.hook,draft.script,draft.caption,draft.cta,json(draft.hashtags),draft.estimatedDuration,json(draft.warnings),json(draft.scenes));
        persistClaims(contentId,draft);const v=db().prepare(`INSERT INTO content_variants(id,content_id,platform,hook,script,title,caption,description,hashtags,cta,target_duration,visual_direction,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,'RenderPlan automático','CONTENT_READY')`);variants.forEach(x=>v.run(newId("variant"),contentId,x.platform,x.hook,x.script,x.title,x.caption,x.description,x.hashtags.join(" "),x.cta,x.targetDuration));
        db().prepare(`INSERT INTO render_plans(id,content_id,status,aspect_ratio,target_duration,plan_json) VALUES(?,?,'NEEDS_MEDIA',?,?,?)`).run(planId,contentId,plan.aspectRatio,plan.targetDuration,json(plan));db().prepare("UPDATE ideas SET status='SELECTED' WHERE id=?").run(ideaId);
      }
      db().exec("COMMIT");
    }catch(e){db().exec("ROLLBACK");throw e}
    logSelection(`persistence completed duration=${Date.now()-step}ms`);
    if(persistedPlanId){stage="asset-resolution";step=Date.now();await resolveRenderPlanAssets(persistedPlanId);logSelection(`asset resolution completed duration=${Date.now()-step}ms`)}
    logSelection(`redirect studio content=${persistedContentId} duration=${Date.now()-startedAt}ms`);return persistedContentId;
  }catch(error){
    if(topicId&&["master-content","variants","render-plan"].includes(stage))usage(p,stage==="master-content"?"GENERATE_CONTENT":stage==="variants"?"GENERATE_VARIANTS":"GENERATE_RENDER_PLAN",topicId,undefined,error);
    console.error(`[idea-select] failed stage=${stage} duration=${Date.now()-startedAt}ms error=${safeMessage(error)}`);throw error;
  }
}
function validateSources(claims:Array<{sourceItemIds:string[]}>,references:string[],topic:TopicContext){const allowed=new Set(topic.sourceItems.map(item=>item.id));if(!references.length||references.some(id=>!allowed.has(id))||claims.some(claim=>!claim.sourceItemIds.length||claim.sourceItemIds.some(id=>!allowed.has(id))))throw new Error("AI_SOURCE_REFERENCE_INVALID")}
function persistClaims(contentId:string,d:MasterContent){const ci=db().prepare("INSERT INTO factual_claims(id,content_id,claim_text,confidence,status) VALUES(?,?,?,?,?)"),si=db().prepare("INSERT OR IGNORE INTO claim_supports(claim_id,source_item_id) VALUES(?,?)");for(const c of d.factualClaims){const id=newId("claim");ci.run(id,contentId,c.text,c.confidence,"EXTRACTED");c.sourceItemIds.forEach(s=>si.run(id,s))}}
export async function generateVariantsForContent(contentId:string){const c=one<Row>("SELECT * FROM contents WHERE id=?",contentId);if(!c)throw new Error("CONTENT_NOT_FOUND");const p=getAIProvider();if(!p.available)throw new Error("AI_NOT_CONFIGURED");const master=masterContentSchema.parse({title:c.title,thesis:c.thesis,hook:c.master_hook,script:c.master_script,caption:c.caption_base,cta:c.cta,hashtags:JSON.parse(String(c.hashtags)),estimatedDuration:c.estimated_duration,factualClaims:all<Row>("SELECT claim_text,confidence FROM factual_claims WHERE content_id=?",contentId).map(x=>({text:String(x.claim_text),confidence:x.confidence,sourceItemIds:all<Row>("SELECT source_item_id FROM claim_supports cs JOIN factual_claims fc ON fc.id=cs.claim_id WHERE fc.content_id=? AND fc.claim_text=?",contentId,String(x.claim_text)).map(s=>String(s.source_item_id))})),sourceReferences:all<Row>("SELECT DISTINCT cs.source_item_id FROM claim_supports cs JOIN factual_claims fc ON fc.id=cs.claim_id WHERE fc.content_id=?",contentId).map(x=>String(x.source_item_id)),warnings:JSON.parse(String(c.warnings)),scenes:JSON.parse(String(c.scenes))});const drafts=await p.generatePlatformVariants(master);usage(p,"GENERATE_VARIANTS",String(c.topic_id),contentId);const st=db().prepare(`INSERT INTO content_variants(id,content_id,platform,hook,script,title,caption,description,hashtags,cta,target_duration,visual_direction,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,'RenderPlan automático','CONTENT_READY') ON CONFLICT(content_id,platform) DO UPDATE SET hook=excluded.hook,script=excluded.script,title=excluded.title,caption=excluded.caption,description=excluded.description,hashtags=excluded.hashtags,cta=excluded.cta,target_duration=excluded.target_duration`);drafts.forEach(x=>st.run(newId("variant"),contentId,x.platform,x.hook,x.script,x.title,x.caption,x.description,x.hashtags.join(" "),x.cta,x.targetDuration));return drafts.length}
