import { DatabaseSync } from 'node:sqlite'; import {resolve} from 'node:path';
const db=new DatabaseSync(resolve(process.env.DATABASE_PATH||'./data/content-os.db')); const now=Date.now(), iso=(m=0)=>new Date(now-m*60000).toISOString();
db.exec('PRAGMA foreign_keys=ON; BEGIN'); try {
db.prepare('INSERT OR IGNORE INTO workspaces(id,name) VALUES(?,?)').run('ws-main','Content Lab');
db.prepare(`INSERT OR REPLACE INTO brands(id,workspace_id,name,niche,target_audience,persona,tone,language,editorial_aggressiveness,controversy_appetite,virality_priority,freshness_priority,factual_invention_tolerance,preferred_topics,avoided_topics,preferred_vocabulary,avoided_vocabulary,cta_preferences,target_platforms,content_objectives,default_formats) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run('brand-radar','ws-main','Radar Pop','Celebridades, entretenimento, cultura pop e acontecimentos virais','Brasileiros interessados em cultura pop','Ágil, curioso e bem informado','Direto, intenso e factual','pt-BR','HIGH','HIGH','HIGH','VERY_HIGH','ZERO','conflito, reviravolta, reação, bastidores','tragédias especulativas, diagnóstico sem fonte','repercussão, resposta, detalhe','certeza sem confirmação, chocante sem base','perguntas que estimulem discussão','TIKTOK,INSTAGRAM,YOUTUBE_SHORTS,FACEBOOK,KWAI','atenção, retenção, compartilhamento','vídeo vertical, post contextual');
const sources=[['src-1','Canal oficial de Luna Vale','SOCIAL_PROFILE','https://example.test/luna',95],['src-2','Revista Prisma Pop','WEBSITE','https://example.test/prisma',82],['src-3','Radar de Tendências','TREND_SOURCE','https://example.test/trends',55]]; for(const [id,n,t,u,r] of sources)db.prepare('INSERT OR REPLACE INTO sources(id,brand_id,name,type,url,enabled,priority,reliability,category) VALUES(?,?,?,?,?,1,?,?,?)').run(id,'brand-radar',n,t,u,80,r,'entretenimento');
const items=[['item-1','src-1','Vídeo público esclarece discussão','Luna Vale publicou uma resposta em seu perfil oficial.','origin-luna'],['item-2','src-2','Nico Prado responde Luna Vale','A revista registrou a resposta pública e a reação dos fãs.','origin-prisma'],['item-3','src-3','Rumor de anúncio cresce nas buscas','Menções aceleram, mas não existe confirmação oficial.','origin-rumor'],['item-4','src-1','Maya Sol anuncia projeto acústico','Anúncio foi publicado no canal oficial da artista.','origin-maya'],['item-5','src-2','Vídeo de Teo Mar viraliza após reação','Um trecho fictício ganhou comentários e compartilhamentos.','origin-video']]; for(const [id,s,t,sm,p] of items)db.prepare('INSERT OR REPLACE INTO source_items(id,source_id,external_id,title,url,published_at,discovered_at,summary,processing_status,provenance_group) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,s,id,t,`https://example.test/${id}`,iso(45),iso(35),sm,'CLUSTERED',p);
const topics=[['topic-a','Discussão pública entre Luna Vale e Nico Prado','Uma troca pública de declarações entre dois influenciadores fictícios ganhou nova resposta e dividiu fãs.','BREAKING',96,94,91,24,97,'conflito,resposta pública,torcida,aceleração',18],['topic-b','Rumor de anúncio surpresa de Zuri Martins','Buscas e menções sobre um possível anúncio fictício aceleram, ainda sem confirmação primária.','VERY_FRESH',98,32,96,18,94,'surpresa,curiosidade,momentum,rumor',12],['topic-d','Vídeo de Teo Mar provoca reação inesperada','Um vídeo fictício ganhou tração rápida depois de uma reação inesperada do público.','VERY_FRESH',87,78,89,31,88,'vídeo viral,reação,surpresa',28],['topic-e','Lia Monte e Ravi Luz publicam reconciliação','Os artistas fictícios publicaram registros confirmando uma reconciliação profissional.','FRESH',76,91,63,42,76,'reconciliação,reviravolta',95],['topic-c','Maya Sol anuncia projeto acústico','A artista fictícia confirmou um novo projeto; a informação é sólida, mas cresce lentamente.','FRESH',48,96,34,38,54,'anúncio confirmado,música',120]]; for(const [id,t,s,f,v,c,m,sat,p,sig,mins] of topics)db.prepare('INSERT OR REPLACE INTO topics(id,brand_id,title,summary,category,status,first_detected_at,last_information_at,original_published_at,collected_at,freshness,virality_score,confidence_score,momentum_score,saturation_risk,editorial_priority_score,signals) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,'brand-radar',t,s,'cultura pop','MONITORING',iso(mins),iso(Math.max(5,mins-6)),iso(mins+8),iso(2),f,v,c,m,sat,p,sig);
[['topic-a','item-1',1],['topic-a','item-2',0],['topic-b','item-3',1],['topic-c','item-4',1],['topic-d','item-5',1]].forEach(x=>db.prepare('INSERT OR REPLACE INTO topic_source_items VALUES(?,?,?)').run(...x));
db.prepare('INSERT OR REPLACE INTO ideas(id,topic_id,title,angle,rationale,rank_score,status) VALUES(?,?,?,?,?,?,?)').run('idea-a','topic-a','A resposta que mudou a discussão','Mostrar a cronologia e o ponto verificável que elevou a repercussão','Conflito sustentado por duas publicações, sem extrapolar intenções',93,'SELECTED');
db.prepare('INSERT OR REPLACE INTO contents(id,brand_id,topic_id,idea_id,title,thesis,angle,master_hook,master_script,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run('content-a','brand-radar','topic-a','idea-a','A resposta que reacendeu a discussão','A nova resposta mudou o ritmo da conversa pública.','Cronologia da resposta','A resposta veio — e a discussão ganhou um novo capítulo.','Luna Vale e Nico Prado trocaram declarações públicas. A nova resposta foi publicada hoje e elevou a repercussão. O que sabemos vem dos perfis públicos e da cobertura identificada; interpretações dos fãs continuam sendo opinião.','REVIEW');
const platforms=[['TIKTOK','A resposta veio — e mudou o ritmo da discussão.','Em menos de 40 segundos, entenda a cronologia confirmada.','O detalhe que reacendeu a discussão',35],['INSTAGRAM','A nova resposta colocou a discussão de volta no centro.','Veja os fatos confirmados e deslize para o contexto.','A resposta que movimentou os fãs',45],['YOUTUBE_SHORTS','Por que essa resposta ganhou tanta repercussão?','A cronologia completa, separando publicação de reação.','Entenda a discussão entre Luna e Nico',50],['FACEBOOK','Uma nova resposta reacendeu o debate — este é o contexto.','A troca pública ganhou um capítulo novo. Confira o que foi publicado e o que é apenas interpretação.','Novo capítulo na discussão pública',60],['KWAI','Teve resposta — e agora os fãs estão divididos.','O resumo rápido da troca pública, sem rumor tratado como fato.','Resposta aumenta repercussão',40]]; for(const [p,h,s,t,d] of platforms)db.prepare('INSERT OR REPLACE INTO content_variants(id,content_id,platform,hook,script,title,caption,description,hashtags,cta,target_duration,visual_direction,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(`var-${p.toLowerCase()}`,'content-a',p,h,s,t,`${s} Qual é a sua leitura?`,'Contexto baseado nas fontes vinculadas.','#RadarPop #CulturaPop','Comente sem atacar',d,'Cortes verticais, fontes na tela e ritmo progressivo','DRAFT');
db.prepare('INSERT OR REPLACE INTO social_accounts(id,brand_id,platform,username,display_name,connection_status) VALUES(?,?,?,?,?,?)').run('account-tiktok','brand-radar','TIKTOK','@radarpop.demo','Radar Pop (demo)','DISCONNECTED');
db.prepare('INSERT OR REPLACE INTO publications(id,content_variant_id,social_account_id,scheduled_for,status) VALUES(?,?,?,?,?)').run('pub-1','var-tiktok','account-tiktok',new Date(now+86400000).toISOString(),'SCHEDULED');
db.exec("UPDATE sources SET data_classification='FIXTURE',enabled=0 WHERE id IN('src-1','src-2','src-3'); UPDATE source_items SET data_classification='FIXTURE' WHERE id LIKE 'item-%'; UPDATE topics SET data_classification='FIXTURE',priority_score=editorial_priority_score,saturation_score=saturation_risk,freshness_score=CASE freshness WHEN 'BREAKING' THEN 100 WHEN 'VERY_FRESH' THEN 85 WHEN 'FRESH' THEN 65 WHEN 'AGING' THEN 30 ELSE 10 END,first_seen_at=first_detected_at,last_seen_at=last_information_at WHERE id LIKE 'topic-%';");
db.exec('COMMIT'); console.log('seeded Radar Pop vertical slice'); } catch(e){db.exec('ROLLBACK');throw e} finally {db.close()}
