import { headlineSimilarity, normalizeText } from "./normalize.ts";

export type ClusterItem={id:string;sourceId:string;title:string;summary:string;publishedAt:string;reliability:number;provenanceGroup:string|null;dependsOnSourceId:string|null;country:string;category:string};
export function shouldCluster(a:ClusterItem,b:ClusterItem){const hours=Math.abs(new Date(a.publishedAt).valueOf()-new Date(b.publishedAt).valueOf())/3_600_000;if(hours>48)return false;return headlineSimilarity(a.title,b.title)>=.42||headlineSimilarity(`${a.title} ${a.summary}`,`${b.title} ${b.summary}`)>=.5;}
export function clusterItems(items:ClusterItem[]){const clusters:ClusterItem[][]=[];for(const item of items){const existing=clusters.find(cluster=>cluster.some(other=>shouldCluster(item,other)));if(existing)existing.push(item);else clusters.push([item]);}return clusters;}
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
export function scoreCluster(items:ClusterItem[],now=new Date()){
 const origins=new Set<string>(),sources=new Set(items.map(item=>item.sourceId));for(const item of items)origins.add(item.dependsOnSourceId?`source:${item.dependsOnSourceId}`:item.provenanceGroup?`origin:${item.provenanceGroup}`:`source:${item.sourceId}`);
 const independent=origins.size,quality=items.reduce((sum,item)=>sum+item.reliability,0)/items.length,dates=items.map(item=>new Date(item.publishedAt).valueOf()).filter(Number.isFinite),first=Math.min(...dates),last=Math.max(...dates),ageMinutes=Math.max(0,(now.valueOf()-last)/60000),windowMinutes=Math.max(5,(last-first)/60000),velocity=Number((items.length/(windowMinutes/60)).toFixed(2));
 const freshness=clamp(100-ageMinutes/14.4),corroboration=clamp(independent*22+quality*.35),momentum=clamp(velocity*13+independent*8),virality=clamp(35+items.length*8+momentum*.35),saturation=clamp(Math.max(0,items.length-8)*8+ageMinutes/120),novelty=clamp(100-saturation-ageMinutes/60),confidence=clamp(quality*.55+corroboration*.45-(items.some(i=>i.dependsOnSourceId)?8:0)),priority=clamp(freshness*.22+momentum*.2+virality*.18+corroboration*.17+quality*.13+novelty*.1-saturation*.12);
 const combined=normalizeText(items.map(item=>`${item.title} ${item.summary}`).join(" ")),conflicting=/nega|desmente|não aconteceu|nao aconteceu/.test(combined)&&/confirma|confirmou|aconteceu/.test(combined),rumor=/rumor|supost|alega|possível|possivel/.test(combined),official=/oficial|confirmou|anunciou|comunicado/.test(combined);
 const factualStatus=conflicting?"CONFLICTING":official||independent>=2&&confidence>=70?"CONFIRMED":rumor&&confidence<55?"RUMOR":confidence<35?"LOW_CONFIDENCE":"DEVELOPING";
 return{independentSourceCount:independent,sourceIds:[...sources],corroborationScore:corroboration,firstSeenAt:new Date(first).toISOString(),lastSeenAt:new Date(last).toISOString(),velocity,freshnessScore:freshness,sourceQualityScore:clamp(quality),noveltyScore:novelty,confidenceScore:confidence,viralityScore:virality,momentumScore:momentum,saturationScore:saturation,priorityScore:priority,factualStatus};
}
export function classifyCategory(title:string,summary:string,country:string){const text=normalizeText(`${title} ${summary}`);const rules:Array<[string,RegExp]>=[["REALITY",/bbb|reality|fazenda/],["TV",/novela|televis|programa/],["CINEMA_STREAMING",/filme|cinema|netflix|streaming|serie/],["MUSICA",/cantor|cantora|musica|album|show/],["INFLUENCERS",/influenciador|influencer|tiktoker|youtuber/],["VIRAL",/viral|internet|redes sociais/],["ESPORTES_ENTRETENIMENTO",/futebol|jogador|atleta|esporte/]];return rules.find(([,pattern])=>pattern.test(text))?.[0]??(country==="BR"?"CELEBRIDADES_BR":country==="US"?"CELEBRIDADES_INTERNACIONAL":"NOTICIAS_GERAIS");}
